### ISSUE TITLE
How to get php users online?

### ISSUE THREAD

**Issue by IDevastated** [Wruczek/ts-website#10]
How to get php users online(number)?

**Comment by Wruczek** [comment]
Can you expand your question? What do you mean by "php users online"?

**Comment by IDevastated** [comment]
How to get the number of online users (php parameter)

**Comment by Wruczek** [comment]
```php
require_once __DIR__ . "/../include/tsutils.php";
$response = pingTeamspeakServerFromConfig();
echo $response["virtualserver_clientsonline"] - $response["virtualserver_queryclientsonline"];
```
You dont need to subtract the number of query clients since ``tsutils`` already ignores them by ``no_query_clients``, but it is a good habit.

**Comment by IDevastated** [comment]
stats not work
php code:
`$json_date = array(
            "success"           => $response["virtualserver_status"] == "online",
            "name"              => $response["virtualserver_name"],
            "clientsonline"     => $response["virtualserver_clientsonline"] - $response["virtualserver_queryclientsonline"],
            "maxclients"        => $response["virtualserver_maxclients"],
            "version"           => TeamSpeak3_Helper_Convert::versionShort($response["virtualserver_version"]),
            "platform"          => $response["virtualserver_platform"],
            "uptime"            => TeamSpeak3_Helper_Convert::seconds($response["virtualserver_uptime"], false, "%dd %02dh %02dm"),
            "averagePacketloss" => $response["virtualserver_total_packetloss_total"],
            "averagePing"       => $response["virtualserver_total_ping"]
        );
header('Content-Type: application/json');
echo json_encode($json_date);`

return:
`{"success":false,"name":null,"clientsonline":0,"maxclients":null,"version":{},"platform":null,"uptime":"0d 00h 00m","averagePacketloss":null,"averagePing":null}`

**Comment by Wruczek** [comment]
You need to include proper libraries.
```php
require_once __DIR__ . "/../include/tsutils.php";
```

**Comment by IDevastated** [comment]
FIXED! :) Thx
