### ISSUE TITLE
Problems encountered while connecting to the TeamSpeak

### ISSUE THREAD

**Issue by R3Z4N4CHR** [Wruczek/ts-website#101]
Problems encountered while connecting to the TeamSpeak server
#0: connection to server '**.118.**.60:10011' lost

**Comment by Wruczek** [comment]
Are you able to connect with other tools, like YaTQA?
This is probably not a problem with TS-website.

**Comment by R3Z4N4CHR** [comment]
Oh i fixed it i have some problems with anti flood! Now when i press login code sending to music bot?

**Comment by Wruczek** [comment]
Probably you have the same IP address as a musicbot

**Comment by R3Z4N4CHR** [comment]
Music bot is connect with VPS like my server

**Comment by Wruczek** [comment]
IP-login issues will be soon be fixed with another login method.
https://github.com/Wruczek/ts-website/projects/1#card-16068499
