### ISSUE TITLE
Install - error

### ISSUE THREAD

**Issue by ondrani** [Wruczek/ts-website#102]
https://i.zerocz.eu/ja/byAsEt8dGu.png

Apache2
php 7.2

**Comment by alexandre433** [comment]
Did you do what it said there?

**Comment by ondrani** [comment]
I don't know how run composer update

**Comment by alexandre433** [comment]
The first part, go to the releases, download it and upload it.

**Comment by Wruczek** [comment]
It literally says what you should do
