### ISSUE TITLE
Ban page HTTP ERROR 500

### ISSUE THREAD

**Issue by flw55** [Wruczek/ts-website#103]
Banlist doesn't work after update.
It works only if the banlist is empty.
If I add ban, then: HTTP ERROR 500

**Comment by toster234** [comment]
Did you add new words for translation?
Update added a few phrases.

**Comment by flw55** [comment]
Ok, I translated it by myself, so I didn't want to add new translations.
Do you know which phrases has been added?

**Comment by toster234** [comment]
Why you translated this yourself, Czech language is added in 2.0.1. If u you don’t want update the language, search missing phrases on onesky We don’t support own translate, you can add your language on OneSky http://wruczek.oneskyapp.com/collaboration/project/index/id/325562

**Comment by toster234** [comment]
You solved the problem?

**Comment by Wruczek** [comment]
If you have error 500, go to the web server's logs and post the `error.log` on pastebin

**Comment by djalmasi** [comment]
> Banlist doesn't work after update.
> It works only if the banlist is empty.
> If I add ban, then: HTTP ERROR 500

If you try to add the new BAN panel separately, it won't work. 
I've tried it in several ways, and only worked when if reinstalled the full web with new installer (2.0.1) version.
