### ISSUE TITLE
Protect query_password

### ISSUE THREAD

**Issue by molidev** [Wruczek/ts-website#110]
Good morning, I saw on the database that query_password it´s store on text-plain.I would recommend you that store this field encrypt with (for example SHA-512)

**Comment by Wruczek** [comment]
Query password is not used for user authentication, it is [send to the TeamSpeak Query Interface in the plaintext form](https://github.com/planetteamspeak/ts3phpframework/blob/master/libraries/TeamSpeak3/Node/Host.php#L815-L833). One-way hashing functions (like SHA*) will not work for that purpose.

The only option here would be not to hash, but to encrypt it. But I don't think it's worth it.

**Comment by Bluscream** [comment]
The only thing we can do is base64encode/decode so it's not completely obvious

**Comment by Wruczek** [comment]
Yeah, that will improve security by a lot XD

**Comment by Bluscream** [comment]
> 
> 
> Yeah, that will improve security by a lot XD

Well, it will scare people that think everything with a = at the end is encrypted and the people that are too stupid to decode it.
