### ISSUE TITLE
Error 111: Connection refused // Error 110: Connection timed out

### ISSUE THREAD

**Issue by tuviejaen4** [Wruczek/ts-website#112]
Hi guys i'm installing site web and i have problem in "Query Details" https://imgur.com/a/r5SF0xx .. help me please.

**Comment by haideranjum** [comment]
You installed MySQL by following any guide step by step?
looks like you're missing some step while installing MySQL.
https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-in-ubuntu-16-04
that guide will help you.

**Comment by nutellazpw** [comment]
I have that error too.
All was installed corectly

**Comment by djalmasi** [comment]
You trying to connect remote? so the ts3 server and the webspace landing on another point? or trying to connect on localhost ?

**Comment by toster234** [comment]
Are you able to connect with other tools, like YaTQA?

**Comment by nutellazpw** [comment]
> 
> 
> You trying to connect remote? so the ts3 server and the webspace landing on another point? or trying to connect on localhost ?

Yea,site and ts3 is not at same server.

**Comment by djalmasi** [comment]
> > You trying to connect remote? so the ts3 server and the webspace landing on another point? or trying to connect on localhost ?
> 
> Yea,site and ts3 is not at same server.

And you are using the custom firewall rules on the vps? Because the firewallrules can block the remote connect. Add the remote ip to TS3 query whitelist txt and check the port opening for all incoming connects. Try to connect yatqa or another program and if it work then really the problem on this website.

**Comment by Wruczek** [comment]
Connection issues are usually not caused by TS-website. If you can prove that this is in fact a bug, feel free to comment and I will reopen this issue.
