### ISSUE TITLE
PGSQL support

### ISSUE THREAD

**Issue by alsoGAMER** [Wruczek/ts-website#113]
Add the support for pgsql databases and use redis for caching

**Comment by Wruczek** [comment]
For PSQL, we use Medoo as a PDO wrapper and it supports PSQL.
So technically, you should be able to use PSQL by modifying `private/dbconfig.php` and setting:
```php
"database_type" => "mysql"
```
to
```php
"database_type" => "pgsql"
```

---

As for the official, out-of-the-box support for both PSQL and Redis, I don't see any benefits in that

PSQL:
- MySQL / MariaDB is much more popular than PSQL
- PSQL is not giving us any significant benefits
- PSQL can probably be already used with the simple config modification, and it's fine considering how few people use it

Redis:
- Minor speed gains, more complicated website installation = no one would use it
- TS-website is already fast
- TS-website installations are usually low on traffic, not used by many people at once and does not require robust in-memory caching like Redis

**Comment by Wruczek** [comment]
No response after 7 days, closing
