### ISSUE TITLE
New setup - not receiving poke upon Login with code.

### ISSUE THREAD

**Issue by jamiew0w** [Wruczek/ts-website#114]
Hey guys,

So I set this up on one of my VM's and everything appears to look okay, it recognises me as an admin in the sidebar but when I try use login or assigner, the page never updates or pokes me with any code.

This is irrespective of whether I connect to ts3 on a new tab, only tab or anything like that. I telnetted in to confirm the query options are correct and I'm not seeing any errors in the logs. The IP is whitelisted for querying also.

Any ideas what may be going wrong?

**Comment by Wruczek** [comment]
TS-website looks up users by IP addresses. In other words: make sure that the TeamSpeak server sees the same IP as your webserver.
Also I'm gonna push a small update to make it easier to debug those issues.

**Comment by Wruczek** [comment]
Ok, you can replace your [`css/style.css`](https://github.com/Wruczek/ts-website/blob/119443bbe89f23b3c48f5daf8415c06659ffd514/src/css/style.css) and [`private/templates/utils/modal-login.latte`](https://github.com/Wruczek/ts-website/blob/119443bbe89f23b3c48f5daf8415c06659ffd514/src/private/templates/utils/modal-login.latte) with the new versions that show the IP's detected by TS-website. Hover over the π in the bottom-right corner to display it.

**Comment by jamiew0w** [comment]
Aha, very good! This is likely going to be down to the reverse proxy not passing through the correct IP address, I'll get to work on resolving that on my end.

Thanks for your quick reply @Wruczek , I'll update this comment afterwards.

Okay, so after updating nginx to correctly forward on real IP address it still wasn't working, but I did manage to diagnose why. I have a mikrotik 10g switch between my servers so it likes to forward the switch IP instead of real IP (ironic, right?) if testing on LAN. This is something I've been meaning to fix for a while, but it hasn't caused any problems, until now.

Anyways, if I hop on a VPN and access everything from outside my network, it works just fine - poke works and I get the code.

Thanks again @Wruczek , we can close this comment out as it is related to my network and not your code - thanks for your help in pinpointing it, appreciated :D
