### ISSUE TITLE
Looks like you have failed file permission checks.

### ISSUE THREAD

**Issue by nosequeponer123** [Wruczek/ts-website#115]
Hello i'm installing site web and I found the following error http://prntscr.com/mrt84h

**Comment by toster234** [comment]
You have written what command u need to use.

**Comment by nosequeponer123** [comment]
yes and... http://prntscr.com/mrwc1q

**Comment by Wruczek** [comment]
Do what the installer says - install CURL

**Comment by nosequeponer123** [comment]
How to install curl? xD

**Comment by Wruczek** [comment]
https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation
