### ISSUE TITLE
Securing private directory [there is no text]

### ISSUE THREAD

**Issue by nosequeponer123** [Wruczek/ts-website#116]
http://prntscr.com/msng8f

**Comment by toster234** [comment]
[work in progress]

**Comment by nosequeponer123** [comment]
Ok, how do I set up the site? For example http://prntscr.com/msnk83

**Comment by toster234** [comment]
To configure the page you must use the mysql client like adminer or phpmyadmin.

**Comment by nosequeponer123** [comment]
Have you ever thought about making a YouTube video? xD

**Comment by toster234** [comment]
This is development release, if you don't know you how to use this, just wait for official release.

1. Download adminer file https://www.adminer.org/
2. Rename file to adminer.php
3. Put adminer.php in main www folder 
4. Go to www.DOMAIN.com/adminer.php
5. Login with your database user

And there you have all stuff

**Comment by Wruczek** [comment]
[Added.](https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Securing-private-directory)
