### ISSUE TITLE
Clean install - Error 500

### ISSUE THREAD

**Issue by PWNYYY** [Wruczek/ts-website#118]
Hi,
i installed the TS-Website successfully and i got this Error..
http://prntscr.com/mw0rkp
Any Solutions?

**Comment by alexandre433** [comment]
Check the logs

**Comment by PWNYYY** [comment]
where can i find the logs?

**Comment by toster234** [comment]
You need to follow installation guide.
https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation#version-for-dummies---step-by-step-with-commands

**Comment by Wruczek** [comment]
Check your server logs, or create a file called `dev_mode` in the private folder

**Comment by PWNYYY** [comment]
i done this. The installation was successful.

**Comment by PWNYYY** [comment]
Okay, now i got this: http://prntscr.com/mw0wt0

**Comment by Wruczek** [comment]
`insufficient client permissions`

**Comment by RealPwned** [comment]
wut

**Comment by RealPwned** [comment]
The ServerQuery has all Permissions.. hm

**Comment by PWNYYY** [comment]
Okay, i found a Solution.
The newest Teamspeak 3 Server Version 3.6.1 has some problems with yatqa and some other things..

//close

**Comment by Wruczek** [comment]
Remember to remove the `dev_mode` file

**Comment by PWNYYY** [comment]
yes! thank your for help @all
