### ISSUE TITLE
How to change favicon.ico ?

### ISSUE THREAD

**Issue by PWNYYY** [Wruczek/ts-website#119]

**Comment by toster234** [comment]
Just add to main www folder where is ts-website installed, file named “favicon.ico”

**Comment by PWNYYY** [comment]
done. But i got the old one..
STRG + F5 (refresh) doesnt help ._.

**Comment by toster234** [comment]
Try CTRL+ALT+F5

W dniu śr., 13.03.2019 o 18:56 RealPwned <notifications@github.com>
napisał(a):

**Comment by PWNYYY** [comment]
Nope, doesnt work :/

**Comment by toster234** [comment]
If you are using cloudflare, try to purge cache
![cloudflare](https://i.imgur.com/Fy7tSD6.png)

**Comment by PWNYYY** [comment]
i dont use cloudflare

**Comment by Wruczek** [comment]
@toster234 Not true, adding a file is not enough 

@RealPwned replace `img/icons/defaulticon-16.png` with your favicon, or change the [favicon path](https://github.com/Wruczek/ts-website/blob/2.0/src/private/templates/body.latte#L15)

**Comment by PWNYYY** [comment]
thank you <3
