### ISSUE TITLE
Admin Status

### ISSUE THREAD

**Issue by irevlix990** [Wruczek/ts-website#120]
hy, i want to ask.. why in my ts-website couldn't show admin server in admin status? how to show admin user in admin status? i don't know how to add it
thx

**Comment by toster234** [comment]
https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation#admin-status-config

**Comment by AwesomeCL** [comment]
I ask that in telegram. So u have instructions in installation wiki but u need add this setting in database. So for admin status and group assigner u need add config in database.

**Comment by Wruczek** [comment]
Please refer to the wiki
