### ISSUE TITLE
Install - Step 3

### ISSUE THREAD

**Issue by Zeemaister** [Wruczek/ts-website#121]
Error 0: SQLSTATE[HY000] [2002] Connection refused

I'm trying install to VPS.

**Comment by Wruczek** [comment]
Either your database server is offline, or you are entering invalid IP

**Comment by Zeemaister** [comment]
I'm using this "https://game-os.de/download/gameos-multiscript.sh.x" script. I'm installing PHP7.2, MySQL, Apache2, PHPMyAdmin from this script to my VPS server.

**Comment by Wruczek** [comment]
Are you able to login to MySQL via phpmyadmin?

**Comment by Zeemaister** [comment]
But i'm trying to install TeamSpeak TSN Ranksystem and error in the first step "Database settings". (Sorry for my bad english)

**Comment by Wruczek** [comment]
I asked if you are able to connect to the database. If TSN also gives you this error then check your database server

**Comment by Zeemaister** [comment]
No. I can't enter to my phpMyAdmin. "mysqli_real_connect(): (HY000/1698): Access denied for user 'root'@'localhost'" . "#1698 - Access denied for user 'root'@'localhost'"

**Comment by Zeemaister** [comment]
Ok. Im enter to phpmyadmin and trying to complete this step 3, but now "Error 0: SQLSTATE[HY000] [1044] Access denied for user 'phpmyadmin'@'localhost' to database 'tswebsite'".

**Comment by toster234** [comment]
You need to use login data with one you typed when you installing the ts-website

**Comment by Wruczek** [comment]
As the error says, you are using wrong username or password to your database

**Comment by Zeemaister** [comment]
And in the Step 4 what login information need?

**Comment by Wruczek** [comment]
Teamspeak query details, just like it says in the installation
