### ISSUE TITLE
Error 0: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by R3Z4N4CHR** [Wruczek/ts-website#122]
Error 0: SQLSTATE[HY000] [2002] Connection refused

**Comment by derrobin154** [comment]
This is not a problem of TS website but of your MySQL credentials or your MySQL server.
Are the credentials correct? Is the MySQL server the same as the web server? and if not, do you have external access enabled?

**Comment by R3Z4N4CHR** [comment]
Yup i fixed it , wrong hostname.. now i need to add an admin stats but there is no info where i need to put the groups id on [Wiki]( https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation)

**Comment by toster234** [comment]
In database.

**Comment by derrobin154** [comment]
toster was fast.
Yes, you put the IDs in the Table "{prefix}_config" in the Line "adminstatus_groups" in JSON Format (ex. [9,12,44,52]
