### ISSUE TITLE
Bład przy "Przydzielanie grup "

### ISSUE THREAD

**Issue by PLOliwier** [Wruczek/ts-website#124]
po dodaniu rol wygląda to tak
![obraz](https://user-images.githubusercontent.com/30889917/56854479-66c7d200-6937-11e9-9c28-b6450208a071.png)
O co może chodzić

**Comment by toster234** [comment]
O niezastosowanie się do wiki https://github.com/Wruczek/ts-website/wiki/%5BPL%5D-Instalacja#szablon-konfiguracji-assignera

**Comment by Wruczek** [comment]
Przeczytaj wiki.
