### ISSUE TITLE
HTTP 500 Error after restarting Apache2

### ISSUE THREAD

**Issue by PWNYYY** [Wruczek/ts-website#125]
Hi,
i restarted Apache2 and than i got the HTTP 500 Error.

http://prntscr.com/nkqjsx
http://prntscr.com/nkqkan

Has anyone a fix ?

Thanks

**Comment by Wruczek** [comment]
Delete files (not folders) from `private/cache`

**Comment by PWNYYY** [comment]
Fixed.
Thank you very much!
