### ISSUE TITLE
Broken site

### ISSUE THREAD

**Issue by flw55** [Wruczek/ts-website#126]
Hey,

if you add "something" after index.php, it'll break the site.
E.g. https://ts.wruczek.tech/index.php/something

Try it, you can type whatever you want after /index.php/

Can it be fixed?

**Comment by Wruczek** [comment]
Currently TS-website does not support access from non-root directory. For example, if you were to add another page in another directory, like: `tswebsite.com/page/test.php` it would break as well. This also applies to the [link you provided](https://ts.wruczek.tech/index.php/something).

If you want to fix it, you need to change all the image/style/script URLs in [body.latte](https://github.com/Wruczek/ts-website/blob/2.0/src/private/templates/body.latte)
