### ISSUE TITLE
Login not working / IPv6 not supported

### ISSUE THREAD

**Issue by D3XX3R** [Wruczek/ts-website#127]
I've installed the latest Dev Version on my webserver. But it's not logging in.
I guess that the login via IP is not really compatible with IPv6.

**Comment by Wruczek** [comment]
There's a small π symbol in the bottom-right login modal. Can you screenshot it?

**Comment by D3XX3R** [comment]
![image](https://user-images.githubusercontent.com/48421663/58713663-5afe7e00-83c3-11e9-9db6-d9556df9c7be.png)

**Comment by Wruczek** [comment]
Yep, IPv6 is not supported by TS-website.

What version of TeamSpeak server are you running?
Do you see your IPv6 on the TS server as well?

**Comment by D3XX3R** [comment]
TeamSpeak 3 Server Version: 3.7.1 on Linux
I'm also connected with IPv6 on my TeamSpeak.

**Comment by Wruczek** [comment]
Ok, then you are ready for an TS-website IPv6 update that should be released soon™

**Comment by Wruczek** [comment]
Please check out [dev-2.0.4](https://github.com/Wruczek/ts-website/releases/tag/dev-2.0.4) and let me know if it works for you.

**Comment by D3XX3R** [comment]
Works like a charm. Thank you very much.

**Comment by Wruczek** [comment]
Great, thanks!
