### ISSUE TITLE
Logowanie

### ISSUE THREAD

**Issue by szogi1910** [Wruczek/ts-website#128]
Witam, mam mały problem z logowaniem się na stronie, po uplywie 30 sekund jakie jest zalecane nie loguje mnie automatyczne oraz nie wyskakuje żadne błąd

**Comment by Wruczek** [comment]
Nakieruj na "π" w ekranie logowania i daj SSa z niego.

**Comment by szogi1910** [comment]
https://zapodaj.net/0125314f9e13f.png.html

Z tego co widzę na tsie pokazuje moje ip inne niż na stronie a nie korzystam z żadnych usług typu cloudflare

**Comment by Wruczek** [comment]
Wykrywa jakieś IP od OVH, używasz jakiegoś proxy, VPNa?

**Comment by szogi1910** [comment]
Jedynie co mam to nginax ma opcje odwrocone proxy, które zostało zainstalowane wraz z vestacp
https://pastebin.com/f5sV1Pin

**Comment by Wruczek** [comment]
To jest twój problem. Jeżeli proxy przekazuje prawdziwe IP w jakimś headerze, możesz go wstawić [tutaj](https://github.com/Wruczek/ts-website/blob/2.0/src/private/php/Utils/Utils.php#L120-L124).

**Comment by szogi1910** [comment]
I to mi chodziło. Sam właśnie nie mogłem namierzyć pliku aby wprowadzić te zmiany . Po lekkiej edycji plik powinnien tak wygladac https://pastebin.com/4wbFVvs7
