### ISSUE TITLE
Unable to connect to TS3 server

### ISSUE THREAD

**Issue by Uldin** [Wruczek/ts-website#129]
Hello,

I get the error "Error 111: Connection refused" every time I try not to connect to the server.
how can I solve this problem?
http://prntscr.com/o4xki4

**Comment by Wruczek** [comment]
Make sure your web server can communicate with your TeamSpeak server and that there are no firewalls blocking your connection.

**Comment by Uldin** [comment]
http://prntscr.com/o55tpj although the firewall is closed, I cannot access it.

**Comment by Wruczek** [comment]
There might be other issues with your connection. You need to diagnose it and fix it yourself.

**Comment by Uldin** [comment]
I tried with different hosting but could not find the problem. I think it's a problem with my vps server.

**Comment by Wruczek** [comment]
If you can't connect with other tools like yaTQA or psychokiller web interface, then it might be a problem with your ts3 server

**Comment by Uldin** [comment]
Yatqa and gametracker connections are active, but I cannot link to other scripts

**Comment by Wruczek** [comment]
If YaTQA works then you either use incorrect login details, or your web server have problems connecting

**Comment by Uldin** [comment]
The systems stopped suddenly and didn't work again. Although I reinstalled my server, the problem did not improve. I'm sure I entered all the information correctly.

**Comment by Wruczek** [comment]
Do you have ts website installed, or are trying to install it?

**Comment by Uldin** [comment]
http://keyfi.org/ts
https://losersclub.xyz

I installed these addresses but it didn't work on both

**Comment by Wruczek** [comment]
If you saw the website/status working and then it stopped then your need to whitelist the web server's IP address

**Comment by Uldin** [comment]
http://prntscr.com/o57s0x :(
