### ISSUE TITLE
Problems with install of v2

### ISSUE THREAD

**Issue by FidoAlex** [Wruczek/ts-website#131]
Hi, I do not know why I can not install ts-website, can someone help me? I use Centos. I read the tutorial steps but I did not get anything to make'it work ... please help.
Error here: [https://imgur.com/KzcCXyF](url)

**Comment by alexandre433** [comment]
``Please do not contact us to help with that error.``

Then it also says to run `composer update` but, if you do know what you're doing

**Comment by FidoAlex** [comment]
I make'it to work, the composer was not installed on my server.
