### ISSUE TITLE
permision on specific page or content based on user login

### ISSUE THREAD

**Issue by FidoAlex** [Wruczek/ts-website#132]
If i want to add a new page on the site or content and to be seen only by users logged in, how can i do that ?

**Comment by toster234** [comment]
TSW does not have this function. You have to do it yourself.

**Comment by FidoAlex** [comment]
i know php but the thing is , how can i work with latte? i havnt use this extension, i have try something but it crashes the site.. any help is apreciated

**Comment by Wruczek** [comment]
You can use the assigner example to make it yourself.
