### ISSUE TITLE
Navigation Dropdown

### ISSUE THREAD

**Issue by zockparadies** [Wruczek/ts-website#133]
Hi, how can i make a dropdown menu in the navigation?

**Comment by alexandre433** [comment]
https://lmgtfy.com/?q=how+to+create+a+dropdown+menu+in+html

**Comment by toster234** [comment]
In body.latte _private/templates/body.latte_ search for `<ul class="navbar-nav">`
And use a bootstrap template.
```
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Text on button
        </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="#">BUTTON 1</a>
        <a class="dropdown-item" href="#">BUTTON 2</a>
    </div>
</li>
```

**Comment by zockparadies** [comment]
How i can change it the height of the navbar?

Before Change:
![Unbenan2nt](https://user-images.githubusercontent.com/23559232/64076101-8e9dbc80-ccc0-11e9-8e01-d1485d32a940.PNG)

After Change:
![Unbenannt](https://user-images.githubusercontent.com/23559232/64076103-93fb0700-ccc0-11e9-9d0a-4a436ca8e3a0.PNG)

**Comment by Wruczek** [comment]
You have too much text that's extending the navbar, reduce the text length to fix it.

**Comment by zockparadies** [comment]
ok thanks for the info , i have now test it and the navbar is still so high :/
![pic3](https://user-images.githubusercontent.com/23559232/64079585-5eb6df00-cce9-11e9-9884-c3e5f9741bc3.PNG)

EDIT:
![pic4](https://user-images.githubusercontent.com/23559232/64079616-fddbd680-cce9-11e9-8831-69cb1f6a112e.PNG)

EDIT2:
![pic5](https://user-images.githubusercontent.com/23559232/64079824-c3c00400-ccec-11e9-8dec-ef10de0492f3.PNG)

**Comment by zockparadies** [comment]
Unfortunately, I can not slob html / php so I would be very happy for further help. (google translator)

**Comment by Wruczek** [comment]
You need to put your `li` inside the `ul`, not outside of it.

**Comment by zockparadies** [comment]
Thank you very much! it works!
