### ISSUE TITLE
Cache save and read test Something went wrong! Please make sure that private/cache directory is writable

### ISSUE THREAD

**Issue by TrickShotMLG02** [Wruczek/ts-website#137]
How can i fix it? I am using this version: 
"ts-website-dev-2.0.3-fed9b56"

**Comment by toster234** [comment]
Please make sure that private/cache directory is writable

**Comment by TrickShotMLG02** [comment]
![grafik](https://user-images.githubusercontent.com/43967908/66581928-3ee4c780-eb81-11e9-9b7a-c49b7bafc10f.png)

**Comment by TrickShotMLG02** [comment]
like this?

**Comment by TrickShotMLG02** [comment]
> 
> 
> Please make sure that private/cache directory is writable

how can i do this?

**Comment by Wruczek** [comment]
Files and folders inside the cache directory need to be writable as well

**Comment by TrickShotMLG02** [comment]
![grafik](https://user-images.githubusercontent.com/43967908/66589980-0993a600-eb90-11e9-8e39-0e84e04bf859.png)

**Comment by TrickShotMLG02** [comment]
like that?

**Comment by TrickShotMLG02** [comment]
![grafik](https://user-images.githubusercontent.com/43967908/66590105-4d86ab00-eb90-11e9-92d6-8fc4233207fb.png)
Does this really makes sense?
The test says, that the permissions are correct for the cache folder

**Comment by TrickShotMLG02** [comment]
What means this?

Warning: file_put_contents(cache/ccfe1cf91aa294c9bf205f86365d5354.cache.php): failed to open stream: Permission denied in /var/www/html/TeamSpeak/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php on line 116

**Comment by Wruczek** [comment]
`failed to open stream: Permission denied`

**Comment by TrickShotMLG02** [comment]
what means that?

**Comment by Wruczek** [comment]
PHP does not have permission to write to that file

**Comment by TrickShotMLG02** [comment]
how can i fix all of these problems?

**Comment by Wruczek** [comment]
You need to fix your linux permissions, not sure whats exactly wrong with yours and Im not an expert with Linux perms, but try `chmod`ding and `chown`ing the entire cache directory. You can also try to empty it and let ts-website create all sub-directories

**Comment by TrickShotMLG02** [comment]
chmod 777?
chown www-data?

**Comment by cobs14** [comment]
It finally turns out that the parent directory of the cache is not granted with suitable permission (say, the whole project directory is in the possession of the root user) so PHP failed to create a file within the cache dir. Simply changing the owner of the project solves the problem:

**chmod -R www-data:www-data ts-website** (if you keep using the initial folder name, instead of solely changing the permission of cache dir)

Hopefully this will help someone in need.

**Comment by Wruczek** [comment]
> It finally turns out that the parent directory of the cache is not granted with suitable permission (say, the whole project directory is in the possession of the root user) so PHP failed to create a file within the cache dir. Simply changing the owner of the project solves the problem:
> 
> **chmod -R www-data:www-data ts-website** (if you keep using the initial folder name, instead of solely changing the permission of cache dir)
> 
> Hopefully this will help someone in need.

That's correct, in recent TS-website versions the installer suggests running this command: `sudo chown -R www-data:www-data "{ts-website directory path}"`
