### ISSUE TITLE
FAQ page gone glitchy

### ISSUE THREAD

**Issue by respi02** [Wruczek/ts-website#143]
Hello. I have an issue with the FAQ page.

Version: 2.0.5
PHP: 7
OS: Ubuntu 18.04
Webserver: Apache2
Cloudflare: No

Expected behaviour: Display page as normal
![image](https://user-images.githubusercontent.com/26170166/68117956-0ecde180-feff-11e9-85f8-9a0c3c40bf83.png)

Actual behaviour: When the faq reaches the height of the side panel, it gone glitchy like this
![image](https://user-images.githubusercontent.com/26170166/68118228-c06d1280-feff-11e9-8f98-7a2ccd0a9dcf.png)

Steps to reproduce: Extend the FAQ height more than the side panel

**Comment by Wruczek** [comment]
This is not an issue with TS-website, but an issue with your malformed HTML in the last answer. You forgot to close the `i` tag.

![image](https://user-images.githubusercontent.com/7156344/68157800-aad30980-ff4e-11e9-9793-8ea451ead204.png)
