### ISSUE TITLE
PhpFileCache.php on line 116

### ISSUE THREAD

**Issue by TheSzymek** [Wruczek/ts-website#144]
`Warning: file_put_contents(cache/ccfe1cf91aa294c9bf205f86365d5354.cache.php): failed to open stream: Permission denied in /var/www/clients/client0/web2/web/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php on line 116
`

> Something went wrong! Please make sure that private/cache directory is writable.
> Private/cache directory is not writable, cannot start the test

Cache directory owner "www-data" and chmod 777, not working.

Anybody can help me?

**Comment by Luca-Hiller** [comment]
Try this


sudo chown -R www-data:www-data "Your Path from the Folder"
