### ISSUE TITLE
Mysql Error Codes

### ISSUE THREAD

**Issue by froland20** [Wruczek/ts-website#145]
Hello,

I installed ts-website 2.0 and connected to mysql but i have got error messages from it.
Can you help me?
![tsw](https://user-images.githubusercontent.com/58860010/70820663-8255ef00-1dd9-11ea-97f6-5969302ad5ca.PNG)

**Comment by Wruczek** [comment]
This is an issue with PhpMyAdmin, unrelated to TS-website

**Comment by avsaponchik** [comment]
make sure you running the latest PMA version
