### ISSUE TITLE
JavaScript assigner error

### ISSUE THREAD

**Issue by TheSzymek** [Wruczek/ts-website#149]
Hello, I have JS errors.

PHP ver 7.2
Screens in attach.

Link: http://ts-zadymka.ga/assigner.php/

![1](https://user-images.githubusercontent.com/49736557/73008215-6305a500-3e0e-11ea-96b6-7182f85c8e1e.PNG)
![2](https://user-images.githubusercontent.com/49736557/73008216-639e3b80-3e0e-11ea-9ef2-ead752cba908.PNG)
![3](https://user-images.githubusercontent.com/49736557/73008217-639e3b80-3e0e-11ea-9961-2b2f357d0cd1.PNG)
![4](https://user-images.githubusercontent.com/49736557/73008218-639e3b80-3e0e-11ea-8d08-45bdb38b5802.PNG)

**Comment by Wruczek** [comment]
Why did you added the trailing slash to the URL? Remove it.
