### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Dmgerr** [Wruczek/ts-website#15]
Cześć, dodałem serwer www do whitelisty w ts, wszystkie dane od polaczenia z query sa ok, jednkaze wyskakuje connection timed out.

link:
http://88-100.pl/

**Comment by Dmgerr** [comment]
http://88-100.pl/info.php

**Comment by Dmgerr** [comment]
BTW serwer TS i WWW to nie te same hosty.

**Comment by Wruczek** [comment]
Używasz adresu numberycznego czy hostname?

**Comment by Dmgerr** [comment]
Numeryczny w konfigu połączenia.
