### ISSUE TITLE
Pagination is not working properly

### ISSUE THREAD

**Issue by banitt** [Wruczek/ts-website#150]
After moving forward through pagination, it shows less and less records
![pagination](https://media.giphy.com/media/iE4tvarsNhfM2Jxacv/giphy.gif)

**Comment by Wruczek** [comment]
Pagination works correctly. It looks like that because there's more text on first page than on the others., you can count the rows yourself and notice that each page contains 10 results.

**Comment by banitt** [comment]
No, its not working properly. Last page (5) shows only 4 records. It should show 10 records.

**Comment by toster234** [comment]
It’s correct.  the first page shows 10 results.  if the last one doesn't
have 10 how to display it.

W dniu pt., 7.02.2020 o 16:26 banitt <notifications@github.com> napisał(a):
