### ISSUE TITLE
Query permissions required by TS-website

### ISSUE THREAD

**Issue by 11037luna** [Wruczek/ts-website#153]
Hi,
I have a problem when im in step 4.
After i enter the Query Details the page load, but i can't go to next step.
I got this : Error! $GLOBALS["__REQUIRED_QUERY_PERMS"] is not defined! 
And i don't know how i can fix it ^^
Thanks and sry for my bad english

**Comment by Wruczek** [comment]
Hi, the required perms are not yet collected and displayed there, but you should be able to continue installation without a problem, just use an serverquery account with enough permissions.

**Comment by 11037luna** [comment]
The problem is when i enter the query details i can't go to the next step ^^

**Comment by toster234** [comment]
If you can try to use serveradmin query.

**Comment by Wruczek** [comment]
> The problem is when i enter the query details i can't go to the next step ^^

What happens? Does the page reload? Nothing happens? Try to describe your issue as detailed as you can.

**Comment by 11037luna** [comment]
Ok when i am in step 4 : 
I enter the query details (i test before its work with putty)
I click submit button and the page load.
Nothing happens, just loading and never stop.
Im sry for bad my english again.

**Comment by Wruczek** [comment]
Wait for a few minutes, it should give you a error message that you can paste here.

**Comment by 11037luna** [comment]
I try with serveradmin, same problem.
I try with 10022 (TeamSpeak SSH) same...

**Comment by 11037luna** [comment]
Oh ok, but the page load since more 15 minutes

**Comment by Wruczek** [comment]
The page should timeout in less than a minute. I'm not sure what's wrong with your site.

**Comment by 11037luna** [comment]
Hmmm, i think i should reinstall something.
I going try reinstall properly all requirements, in few days.
I will come back to you when it is done and if I still have the same problem ^^
Thanks for your time.

**Comment by 11037luna** [comment]
I'm back, and sorry for be so long ^^
So i reinstall everything properly and the 'Tswebsite' work fine, thanks you so much.
But i have a question, when i was installing i have enter a display IP but i need to update this information.
I was looking for in the DataBase but i didn't find where i can update.
Thanks again and sorry for my bad english.

**Comment by Wruczek** [comment]
It's in the `tsw_config` table under `query_displayip`
