### ISSUE TITLE
Turkish language time problem

### ISSUE THREAD

**Issue by Uldin** [Wruczek/ts-website#154]
When I used the Turkish language, the old versions showed the time zone correctly. It shows English with the new version.

https://prnt.sc/r6doap

**Comment by Wruczek** [comment]
I've updated translation with the correct value.

If you want to fix it on your site, run:
```sql
UPDATE `tsw_translations` SET `value`='tr' WHERE `identifier` = 'MOMENTJS_LANG' AND `langid` = 17
```
