### ISSUE TITLE
After PHP reinstall -> Cannot retrieve server status

### ISSUE THREAD

**Issue by PWNYYY** [Wruczek/ts-website#155]
Hi,
i reinstalled php7.3 and removed older versions and now the Website cannot retrieve server status.
All other works fine. Any solutions?

![image](https://user-images.githubusercontent.com/44307473/75580812-b3ed6680-5a68-11ea-862e-2c642d94ce60.png)

Thanks

**Comment by Wruczek** [comment]
Visit `/api/getstatus.php` and paste the output.

**Comment by PWNYYY** [comment]
`{"success":true,"generated":1582936157,"data":{"uid":"xi3u4oxk7TqevAmHH612vKRWI54=","name":"TeamSpeak\u00b3 Server","nicknames":"nicknames","channelCount":130,"serverIconId":3528899973,"clientsOnline":8,"maxClients":32,"reservedSlots":0,"onlineRecord":24,"onlineRecordDate":1581626792,"version":"3.11.0","platform":"Linux","uptime":465893,"uptimeFormatted":"5d 09h 24m","averagePacketloss":0.0015,"averagePing":4.125}}`

**Comment by Wruczek** [comment]
Whats your website URL?

**Comment by PWNYYY** [comment]
Thats really weird. I restarted my WebServer and now the Server status displays successfully.
Thank you very much for your help.
