### ISSUE TITLE
Assigner and iPv6

### ISSUE THREAD

**Issue by flw55** [Wruczek/ts-website#156]
Hey,

i started using iPv6 and I found out that the assigner can't recognize that you are connected to TeamSpeak server. I had to disable iPv6 to be able to login to my website.

Fix this please?

**Comment by Wruczek** [comment]
This is related to the IP detected by your web server and if you are able to connect to it with IPv6. Website itself handles IPv6 just fine. Check if you have a correct AAAA record, if your VPS/web server supports them.
