### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by skip850** [Wruczek/ts-website#157]
Cześć, chciałem się przenieść na wersję 2.0 i mam problem.

Konfiguracja przeszła gładko. Przy pierwszym uruchomieniu strona ładowała się z dobre 10 min. W logach na TS było coś takiego, co 10s pobierało ikonę (pobrało może z 10 z 50):

```
18.03.2020 17:11:37	VirtualServerBase	Info	file download from (id:0), '/icon_3707331440' by client 'TS-website'(id:50751)
18.03.2020 17:11:47	VirtualServerBase	Info	file download from (id:0), '/icon_3716920003' by client 'TS-website'(id:50751)
18.03.2020 17:11:57	VirtualServerBase	Info	file download from (id:0), '/icon_3739402688' by client 'TS-website'(id:50751)
```
Po czym wyskoczyły błędy:
```
Notice: Cannot download icon 11068116 in /usr/home/*/domains/*.pl/public_html/private/php/ServerIconCache.php on line 41 // i tak dalej
```

Po załadowaniu strony, wchodząc na strony/bany:

```
Problemy napotkane podczas próby połączenia się z serwerem TeamSpeak
#60: Operation timed out
```
Czasami strona załaduje statystyki, czasami nie.
Wszystko działało z poprzednią wersją.

**Comment by Wruczek** [comment]
Check your filetransfer port and if its available to the website. Can other tools download icons (YaTQA)? If you clear your TS3 Client cache, can your client download icons?

**Comment by skip850** [comment]
Its available to the website.
Yes, YaTQA can download all icons.
Yes, it works too.

**Comment by Wruczek** [comment]
Where do you host your website? On your own VPS or a shared hosting?

**Comment by skip850** [comment]
TS on VPS, website hosting (mydevil).

**Comment by Wruczek** [comment]
Contact your hosting provider, ask if they throttle/limit remote connections like those. Ask if the website is allowed to connect to remote port `30033/tcp`. If YaTQA/client works fine then the issue is with the hosting company.
