### ISSUE TITLE
Ban expiration is bugged

### ISSUE THREAD

**Issue by Najsr** [Wruczek/ts-website#16]
When I opened https://ts.wruczek.tech/bans.php I saw that my lang is set to Czech but lang of Permament was Russian. Even when I changed languages it remained the same.

**Comment by Wruczek** [comment]
Yep, the parts of the website gets cached along with the user language. Im aware of this bug, but it has not been resolved yet.

Im leaving this issue open, waiting for fix.

**Comment by Wruczek** [comment]
Fixed in ts-website 2.0
