### ISSUE TITLE
Error 500 after installation languages

### ISSUE THREAD

**Issue by Pyroman-FEAR** [Wruczek/ts-website#161]
hi 
I got an Error 500 after i finished the installation 

The Default lang in the Db is "en-us".
My language in the browser is  "de" (German)

My Error log:

[25-Mar-2020 14:46:18 Europe/Belgrade] PHP Fatal error: Uncaught Exception: Cannot get translation for MOMENTJS_LANG in C:\inetpub\wwwroot\Ts-website\private\php\Utils\Language\LanguageUtils.php:194
Stack trace:
#0 C:\inetpub\wwwroot\Ts-website\private\php\Utils\Language\LanguageUtils.php(26): Wruczek\TSWebsite\Utils\Language\LanguageUtils->translate('MOMENTJS_LANG', Array)
#1 C:\inetpub\wwwroot\Ts-website\private\cache\templates\private-templates-body.latte--001849cdc0.php(310): Wruczek\TSWebsite\Utils\Language\LanguageUtils::tl('MOMENTJS_LANG')
#2 C:\inetpub\wwwroot\Ts-website\private\vendor\latte\latte\src\Latte\Runtime\Template.php(198): Template001849cdc0->main()
#3 C:\inetpub\wwwroot\Ts-website\private\vendor\latte\latte\src\Latte\Runtime\Template.php(176): Latte\Runtime\Template->render()
#4 C:\inetpub\wwwroot\Ts-website\private\vendor\latte\latte\src\Latte\Runtime\Template.php(326): Latte\Runtime\Template->render()
#5 C:\inetpub\wwwroo\Ts-webs in C:\inetpub\wwwroot\Ts-website\private\php\Utils\Language\LanguageUtils.php on line 194

**Comment by Wruczek** [comment]
I've installed `dev-2.0.5.1-d7f5b0`, changed website language to German and it worked fine. Cannot reproduce.
