### ISSUE TITLE
Can´t Login because wrong IP (Reverseproxy)

### ISSUE THREAD

**Issue by Pyroman-FEAR** [Wruczek/ts-website#162]
i had the problem that i could not log in because the site did not use my real IP address but the reverse proxy adress 

in my case it helped to use the "HTTP_X_FORWARDED_FOR" header in the getClientIp function

**Comment by toster234** [comment]
Does the problem persist?

**Comment by Wruczek** [comment]
We are only trusting the real IP address because of security. In rare cases like yours people can just change the Utils class.
