### ISSUE TITLE
Multiple connections / Icons not downloading / PHP version

### ISSUE THREAD

**Issue by GRiveron** [Wruczek/ts-website#163]
Hey guys,

I had a few issues with the tool during installation. I managed to make it work on our site but I have a couple of questions.
Does the tool need both filetransfer_port and query_port open on the host to grab icons and test/grant the connection? I requested our host to open our query port and that solved the connection 110 timed out error, but another issue was that the page did not manage to grab the icons from the server and I had to manually add them as the host support was not replying to messages. 
Another thing was that I had to set up PHP to version 7.0 in order to have the page working properly, version 7.1/7.2/7.3/7.4 got me the following error:

**>  PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated**
Another question, do we have an option to have the bot connections per hour limited or a way to avoid the bot connecting randomly and abandoning the connection immediately?

Kindly waiting for your support on this. / Great tool!

**Comment by Wruczek** [comment]
Hi.

The website needs query connection for all the basic stuff, and filetransfer for icon download.
If the icons are not downloaded then its likely that the filetransfer port (30033) is blocked somehow.

The "Array and string offset access syntax with curly braces is deprecated" warning will only appear with PHP 7.4 and later, it will not show up with PHP under 7.4.

The described behavior - "bot connecting randomly and abandoning the connection immediately" is correct and nothing to worry about. The website connects each time it needs to grab new data.
If you want to limit frequency of website connections to TS3 server, you can extend caching time (`cache_*`) in `tsw_config` table. Status is refreshed pretty often, so you might limit this by changing `cache_serverinfo`.
