### ISSUE TITLE
Question to the website

### ISSUE THREAD

**Issue by ghost** [Wruczek/ts-website#164]
Hi there,

i have a question. Can i copy the design from the website and made a new website with new backend for my project? Is it okay?

**Comment by toster234** [comment]
https://github.com/Wruczek/ts-website/blob/2.0/LICENSE.txt

**Comment by ghost** [comment]
> https://github.com/Wruczek/ts-website/blob/2.0/LICENSE.txt

It means i can do it? I don't know, its many text

**Comment by Wruczek** [comment]
![image](https://user-images.githubusercontent.com/7156344/80833870-cfebc080-8bef-11ea-9c04-73a969a2762e.png)
