### ISSUE TITLE
Cannot load cache file

### ISSUE THREAD

**Issue by retpircs** [Wruczek/ts-website#174]
Hello,

without changing anything on the website or on the server, I got this error yesterday:

`[php7:error] [pid 23829] [client XXX] PHP Fatal error:  Uncaught Exception: Cannot load cache file! (translations) in /var/www/html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php:75\nStack trace:\n#0 /var/www/html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(313): Wruczek\\PhpFileCache\\PhpFileCache->loadCacheFile()\n#1 /var/www/html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(62): Wruczek\\PhpFileCache\\PhpFileCache->reloadFromDisc()\n#2 /var/www/html/private/php/Utils/Language/LanguageUtils.php(30): Wruczek\\PhpFileCache\\PhpFileCache->__construct()\n#3 /var/www/html/private/php/Utils/SingletonTait.php(16): Wruczek\\TSWebsite\\Utils\\Language\\LanguageUtils->__construct()\n#4 /var/www/html/private/php/Utils/SingletonTait.php(26): Wruczek\\TSWebsite\\Utils\\Language\\LanguageUtils::Instance()\n#5 /var/www/html/private/php/load.php(54): Wruczek\\TSWebsite\\Utils\\Language\\LanguageUtils::i()\n#6 /var/www/html/index.php(6): require_once('/var/www/html/p...')\n#7 {main}\n  thrown in /var/www/html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php on line 75`

When I try to access the website, I only see Error 500.
What can i do to fix this?

Best regards
easy

**Comment by retpircs** [comment]
I´m using the version 2.0

**Comment by Wruczek** [comment]
Yep it unfortunately [sometimes happens](https://github.com/Wruczek/PHP-File-Cache/issues/3), and I haven't found a way to fix it. Closing as we have the other issue open.
