### ISSUE TITLE
How to add chrismas.js from ts-website 1.0 to ts-website 2.0.

### ISSUE THREAD

**Issue by froland20** [Wruczek/ts-website#176]
Hello,

I would like to use the chrimast snow effect on the ts website 2.0.
I removed from the script the css file import, and successfully uploaded to js folder with christmas.js.

Imported this code to body.latte: <script src="js/christmas.js"></script>
But when I reloading the page I got syntax error message.

Can you help me?

**Comment by Wruczek** [comment]
I really discourage it, its all JS animation and its very CPU heavy, especially on mobile.
