### ISSUE TITLE
I cant install it

### ISSUE THREAD

**Issue by Atrexianek** [Wruczek/ts-website#177]
Error: Error 0: connection to server '82.208.17.95:10011' lost
I am hosting my ts on FAKAHEDA.eu

**Comment by Wruczek** [comment]
It might be something with your website or TS3 hosting. Its not an issue with TS website. Please contact both of your hosting providers.

**Comment by Atrexianek** [comment]
I have contacted but they told me that I have to contact you. My site: https://gamemaniac.eu/viewer.php

**Comment by Atrexianek** [comment]
Query is connected to my server but I cant see it on website

**Comment by Wruczek** [comment]
> Query is connected to my server but I cant see it on website

Not sure what you mean
