### ISSUE TITLE
viewer.php

### ISSUE THREAD

**Issue by szogun1910** [Wruczek/ts-website#178]
Hej, po czystej instalacji mam problem z zakładką podgląd serwera w momencie gdy dodałem wymuszenie pokazania błędów 

`Fatal error: Uncaught TypeError: Argument 2 passed to Wruczek\TSWebsite\ViewerRenderer::__construct() must be of the type array, null given, called in /home/xxx.pl/public_html/viewer.php on line 15 and defined in /home/xxx.pl/public_html/private/php/ViewerRenderer.php:23 Stack trace: #0 /home/xxx.pl/public_html/viewer.php(15): Wruczek\TSWebsite\ViewerRenderer->__construct() #1 {main} thrown in /home/xxx.pl/public_html/private/php/ViewerRenderer.php on line 23`

**Comment by Wruczek** [comment]
What's your config value of `viewer_hidden_channel_ids`?
