### ISSUE TITLE
Make channels private from the TS viewer

### ISSUE THREAD

**Issue by pix0wl** [Wruczek/ts-website#18]
Hi,

is it possible to hide users from the TS viewer in specified channels?
I've tried it with making a edited duplicate of the server admin query group, but I wasn't able to create login credentials.

Greets

**Comment by Wruczek** [comment]
Good idea, gonna add it to the next version or release. Thanks!

Until the update, there are no easy way of doing this yourself other than editing the [ts3phpframework](https://github.com/Wruczek/ts-website/blob/master/lib/ts3phpframework/libraries/TeamSpeak3/Viewer/Html.php) directly, so unfortunately I cannot give you a quick fix for now.

**Comment by pix0wl** [comment]
Thank you for your friendly reply. I would be very happy about such a function.

**Comment by Wruczek** [comment]
Added in 2.0
