### ISSUE TITLE
array_merge() error

### ISSUE THREAD

**Issue by Fr0zenForest** [Wruczek/ts-website#190]
> Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /www/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php:129 Stack trace: #0 [internal function]: array_merge() #1 /www/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php(129): call_user_func_array() #2 /www/private/vendor/latte/latte/src/Latte/Engine.php(117): Latte\Compiler->compile() #3 /www/private/vendor/latte/latte/src/Latte/Engine.php(186): Latte\Engine->compile() #4 /www/private/vendor/latte/latte/src/Latte/Engine.php(93): Latte\Engine->loadTemplate() #5 /www/private/vendor/latte/latte/src/Latte/Engine.php(80): Latte\Engine->createTemplate() #6 /www/installer/pages/2.php(229): Latte\Engine->renderToString() #7 /www/installer/pages/2.php(29): checkRequirements() #8 /www/installer/index.php(28): require('...') #9 {main} thrown in /www/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php on line 129

PHP version: 8.0.1

Solution:  /www/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php:129
 $this->macros   --->   array_values($this->macros)
and it works,but I don't know what bugs will come next with PHP8...And I am considering downgrading to 7.4

**Comment by Wruczek** [comment]
PHP 8 is not yet officially supported. PHP 7.4 is recommended.

**Comment by Wruczek** [comment]
Leaving #184 open for PHP 8
