### ISSUE TITLE
Google results

### ISSUE THREAD

**Issue by froland20** [Wruczek/ts-website#191]
Hello,

Someone can help me how can I change  the meta tags what the google results as shown in the picture?
I want to change this language to Hungarian and I want to add description.

![Képkivágás](https://user-images.githubusercontent.com/58860010/115104012-27488500-9f56-11eb-80da-9251a8ed688e.PNG)

**Comment by Wruczek** [comment]
For the description, try adding a meta description header [with the other meta headers in body.latte](https://github.com/Wruczek/ts-website/blob/8c93d31321c5385985f2c3af73723db2f5c94a5c/src/private/templates/body.latte#L10):
`<meta name="description" content="A description of the page">`

For the language, im not sure, but you might try changing the default language by editing the `tsw_languages` table. Find the current default langauge (probably english) - it will have `isdefault` set to `1` - change it to `0`. Now find Hungarian and change `isdefault` from `0` to `1`. This will change the default website language.

**Comment by Wruczek** [comment]
Issue is inactive - closing
