### ISSUE TITLE
Channel which should be private is subscribed

### ISSUE THREAD

**Issue by TrickShotMLG02** [Wruczek/ts-website#192]
I have one channel called private, which can't be subscribed by any servergroup. But the query does. How can I fix this?

**Comment by Wruczek** [comment]
To hide a channel from TS-website viewer you can either:
- add channel ID to the config under `viewer_hidden_channel_ids`
- set channel permission `i_channel_needed_subscribe_power` to `75` or higher

**Comment by TrickShotMLG02** [comment]
I can't find viewer_hidden_channel_ids in the configtable of the mysqldb

**Comment by Wruczek** [comment]
My bad, the change in not in any release. I would need to publish a release, or you can update your viewer.php file to [the one in the repo](https://github.com/Wruczek/ts-website/blob/2.0/src/viewer.php) and then add a new config row to the config table:
```sql
INSERT INTO `tsw_config` (`identifier`, `type`, `value`, `user_editable`) VALUES ('viewer_hidden_channel_ids', 'JSON', '[]', 1);
```

Then you can set `viewer_hidden_channel_ids` to the IDs you want.

**Comment by TrickShotMLG02** [comment]
I will try it this afternoon. Thank you for your fast reply

**Comment by TrickShotMLG02** [comment]
I have added the channelid to the db and it is still displaying the channel on the webpage with all the clients which are inside

**Comment by TrickShotMLG02** [comment]
I have added the channelid to the db and it is still displaying the channel on the webpage with all the clients which are inside (After 15 Minutes)

**Comment by Wruczek** [comment]
Are you sure you have updated the `viewer.php` file?

**Comment by TrickShotMLG02** [comment]
I think so. I will try it again

**Comment by TrickShotMLG02** [comment]
It was exact the same content as mentioned previously, so everything should be correct

**Comment by TrickShotMLG02** [comment]
I think I know what the problem is

This is the constructor of the ViewerRenderer:

`public function __construct($imgPath) {
        $this->imgPath = $imgPath;

        $cm = CacheManager::i();
        $this->serverInfo = $cm->getServerInfo();
        $this->channelList = $cm->getChannelList();
        $this->clientList = $cm->getClientList();
        $this->serverGroupList = $cm->getServerGroupList();
        $this->channelGroupList = $cm->getChannelGroupList();
    }
`

And this constructor is getting called
`$viewerRenderer = new ViewerRenderer("img/ts-icons", Config::get("viewer_hidden_channel_ids"));`

I believe, that I also need to update the constructor so there is support for both parameters.
Am I right?

**Comment by TrickShotMLG02** [comment]
I have fixed it, by copying the ViewerRenderer.php from your repo and replacing my old one.

**Comment by Wruczek** [comment]
You are right, more files need to bed edited. I really should publish a new release.

**Comment by TrickShotMLG02** [comment]
Maybe. But you have done a great job with this project. Keep it up.

**Comment by Wruczek** [comment]
We can keep this issue closed, publishing a new release should be a separate issue.
