### ISSUE TITLE
After logging in, open the Group assigner page to report an error

### ISSUE THREAD

**Issue by gwailam** [Wruczek/ts-website#194]
After logging in, open the Group assigner page to report an error, the code is as follows:

`Warning: Invalid argument supplied for foreach() in /www/wwwroot/139.9.70.209/private/php/Assigner.php on line 86‘

'Warning: Invalid argument supplied for foreach() in /www/wwwroot/139.9.70.209/private/php/Assigner.php on line 27'

'Warning: Cannot use a scalar value as an array in /www/wwwroot/139.9.70.209/private/php/Assigner.php on line 42'

'Warning: Cannot use a scalar value as an array in /www/wwwroot/139.9.70.209/private/php/Assigner.php on line 43`

`Warning
: Invalid argument supplied for foreach() in
/www/wwwroot/139.9.70.209/private/cache/templates/private-templates-assigner.latte--5d7733ac0d.php
on line
161`

**Comment by Wruczek** [comment]
- whats your PHP version?
- whats your assigner configuration?

**Comment by gwailam** [comment]
okay,it's working.
