### ISSUE TITLE
Not PHP8.0 compatible?

### ISSUE THREAD

**Issue by ghost** [Wruczek/ts-website#195]
Looks like php8 is not yet compatible as it fails in the installation routine. 

`Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php:129 Stack trace: #0 [internal function]: array_merge() #1 /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php(129): call_user_func_array() #2 /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Engine.php(117): Latte\Compiler->compile() #3 /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Engine.php(186): Latte\Engine->compile() #4 /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Engine.php(93): Latte\Engine->loadTemplate() #5 /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Engine.php(80): Latte\Engine->createTemplate() #6 /var/www/fuwu.at/ts/ts-website/installer/pages/2.php(229): Latte\Engine->renderToString() #7 /var/www/fuwu.at/ts/ts-website/installer/pages/2.php(29): checkRequirements() #8 /var/www/fuwu.at/ts/ts-website/installer/index.php(28): require('...') #9 {main} thrown in /var/www/fuwu.at/ts/ts-website/private/vendor/latte/latte/src/Latte/Compiler/Compiler.php on line 129`
Just letting you know, since the Website says, that php7.2 or above is compatible. 

Cheers!

**Comment by toster234** [comment]
Officially PHP 8 is not yet supported. We recommend using PHP 7.4

**Comment by ghost** [comment]
Ahh okay, my bad, did not find that information. I'll use 7.4. Cheers!
