### ISSUE TITLE
Group assigner

### ISSUE THREAD

**Issue by ZoonGcs** [Wruczek/ts-website#196]
Group assigner is not configured by the website administrator

How can i set icons from TS in DB? Thanks

**Comment by toster234** [comment]
In tabel **tsw_config** search for **assignerconfig** and follow the template from wiki [https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation#assigner-config-format](https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation#assigner-config-format)

**Comment by ZoonGcs** [comment]
Link not working for me,.

**Comment by toster234** [comment]
Wiki > Website Installation

**Comment by ZoonGcs** [comment]
Nice, found it, working. Thanks a lot  <3
