### ISSUE TITLE
Unreadable "dbconfig" file

### ISSUE THREAD

**Issue by byKeksYT** [Wruczek/ts-website#197]
As I tried to install ts-website on my server, at Step 2 I got an error that says:
`Cannot read the db config file! (/var/www/html/ts-website/private/php/../../private/dbconfig.php)`
I set the ownership of the root directory of ts-website to www-data and restarted apache2 after the installation.
Can anyone tell me why I'm getting this error?

**Comment by Wruczek** [comment]
Does the file already exists? Try deleting it.

**Comment by byKeksYT** [comment]
Yes, the file exists, but as I looked info it, it is empty. Is there expected to be any code in there?

**Comment by Wruczek** [comment]
No, it will be auto-filled with data at the end of the installation process. In step 2, it should be created by TS-website (with proper permissions), and the check should pass.

**Comment by byKeksYT** [comment]
At Step 2 I always get this "error": 
![85246c145733acb85bba00dae0342416](https://user-images.githubusercontent.com/54219222/128751210-b0b2cdd3-f59d-4cbc-a9b6-fcfcb4f61e11.png)

**Comment by toster234** [comment]
Try using PHP 7.4. PHP 8 is not supported yet.

**Comment by byKeksYT** [comment]
Okay, thank you for the advice! It works now with PHP 7.4 installed.
