### ISSUE TITLE
pomocy

### ISSUE THREAD

**Issue by awski13371** [Wruczek/ts-website#198]
jak próbuję to zainstalować to nie mogę na vps
a lokalnie jak to insatluje to ok

**Comment by toster234** [comment]
Niestety dużo to nam nie mówi.

**Comment by awski13371** [comment]
wjedz na vps.atlashc.pl to będzesz wiedzał

**Comment by toster234** [comment]
Skorzystaj z poradnika https://github.com/Wruczek/ts-website/wiki/%5BPL%5D-Instalacja#wersja-dla-ba%C5%82wan%C3%B3w---krok-po-kroku-z-komendami

**Comment by awski13371** [comment]
nie działa 51.68.148.7

**Comment by awski13371** [comment]
@toster234 Pomorzesz Czy Nie?
