### ISSUE TITLE
How do I configure website administrator

### ISSUE THREAD

**Issue by siripalagelabba404blabla** [Wruczek/ts-website#206]
When I try to log in to admin panel it says "This is a dev release of ts-website. There is no admin panel yet. Modify the database directly to change the configuration.". How do I fix this please help me?

**Comment by toster234** [comment]
You have written that there is no admin panel which means there is no admin
panel 🤨

**Comment by Wruczek** [comment]
> This is a dev release of ts-website. **There is no admin panel yet.** Modify the database directly to change the configuration.
