### ISSUE TITLE
Server icons

### ISSUE THREAD

**Issue by DeathStrokeAMXXPRO** [Wruczek/ts-website#207]
I don't know why, but the site does not download group icons from the server. Please help me quickly

https://prnt.sc/26q0zzv

**Comment by Wruczek** [comment]
They might not exist on the server. In TS3 client, disconnect from your server, clear you TS3 client cache (Settings -> Security -> Clear cache -> "Clear cache") and rejoin your server. If the icons do not download and you see errors in server chat then the icons on your server are broken.

**Comment by DeathStrokeAMXXPRO** [comment]
thx fixed
