### ISSUE TITLE
Nginx, openlitespeed

### ISSUE THREAD

**Issue by ghost** [Wruczek/ts-website#210]
hi, is your code nginx and openlitespeed ready? I have never had a problem with apache2 but since I changed apache2 to nginx / openlitespeed I always have problem like the screenshot
![ss1](https://user-images.githubusercontent.com/103936546/163803156-b06915e6-f0bf-45ea-b266-8f5bb4a89d59.png)

I tested different settings and nothing helped

**Comment by Wruczek** [comment]
Nginx works without a problem, even the installation tutorial is based on nginx. Visit the image link directly and check what it shows.

**Comment by Wruczek** [comment]
Issue is inactive - closing
