### ISSUE TITLE
Set admins of TeamSpeak server to be displayed in ts-website

### ISSUE THREAD

**Issue by byKeksYT** [Wruczek/ts-website#214]
I have a question regarding the admins of the TeamSpeak server this interface is being used for. In the [installation tutorial](https://github.com/Wruczek/ts-website/wiki/%5BEN%5D-Website-Installation) it is only being said that the admin server group ID should be defined in _the config_. My question is which config file is meant?  In the `/ts-website/private/php/Config.php` I did not find a string that begins with `adminstatus_groups` like it is said in the tutorial. In other files I did not find any matching strings either. So I really have no idea where to set the admins and hope that some of you could help me.

**Comment by toster234** [comment]
All configuration is done through the database. Use phpmyadmin or adminer to edit the database.
