### ISSUE TITLE
Banlist ip check

### ISSUE THREAD

**Issue by cataalin** [Wruczek/ts-website#215]
I have seen that the $ipbanned option was deactivated, I activated it to see how it is but it seems that it does not work well, how can I fix it? He shows me this even though I ban myself. @Wruczek 

![fdsfdsfd](https://user-images.githubusercontent.com/28767431/206680804-d5ef3a54-ee18-4f77-8465-504c01498d6c.jpg)

**Comment by Wruczek** [comment]
If you banned yourself then it's correct that you see the ban information. I do not understand, can you try explaining what is wrong?

**Comment by cataalin** [comment]
> If you banned yourself then it's correct that you see the ban information. I do not understand, can you try explaining what is wrong?

Shouldn't it come out that you are not banned by not being?  because the same thing always comes out, banned or not.

![gfdgdgfd](https://user-images.githubusercontent.com/28767431/206900012-42e820c2-ba27-41c4-acf1-fd401d471c7e.jpg)


Wouldn't it work just like in a post of yours from 2018?


> ![image](https://user-images.githubusercontent.com/7156344/45248918-96c65480-b317-11e8-8857-38622806c86d.png) 👀 no, it's not dead ;)

> ![image](https://user-images.githubusercontent.com/7156344/46217888-85370200-c343-11e8-8523-be077ef74e12.png) I guess the bans page is complete. Finishing the viewer now!



> You don't need to enable this feature - it is on by default. In fact, there is no config for this function. Everyone banned will see this message. I was referring to the fact that you should not edit any files as all the config options are in DB.

I was saying it because I tried an autoban and nothing comes out, but what about this image? when does it appear?

> ![image](https://user-images.githubusercontent.com/7156344/45248918-96c65480-b317-11e8-8857-38622806c86d.png) 👀 no, it's not dead ;)

> ![image](https://user-images.githubusercontent.com/7156344/46217888-85370200-c343-11e8-8523-be077ef74e12.png) I guess the bans page is complete. Finishing the viewer now!

**Comment by Wruczek** [comment]
Yes, it should only show the alert if your IP is banned.
So it shows it every time, even if you are not banned? 
Can you check what IP your website detects? Click on login and hover over the 𝝅 icon:
![image](https://user-images.githubusercontent.com/7156344/206938646-862543ff-764e-440d-aee1-372d19891f06.png)
Now compare it to the IP banned by your TS3 server. Is it the same?

**Comment by cataalin** [comment]
> 

Yes, it shows it the same all the time even if you are not prohibited, the ip is the same as the ts in the debugging, maybe I activate it wrong or something or through the https protocol could it be? I activate it by changing line 12 of bans.php, false to true.

![image](https://user-images.githubusercontent.com/7156344/207473642-99496045-de32-4ea7-85c8-947f59839471.png)
![image](https://user-images.githubusercontent.com/7156344/207473717-e8b55360-7906-457f-8ec1-c960dad63a80.png)

**Comment by Wruczek** [comment]
Line 12 does not activate anything, you have made the site think that everyone is IP banned. The configuration is in database, you don't need to change anything else.

**Comment by cataalin** [comment]
> 

oh, but in the database I don't see anything related to this, not even in the translations, could you tell me where?

**Comment by Wruczek** [comment]
You don't need to enable this feature - it is on by default. In fact, there is no config for this function. Everyone banned will see this message.
I was referring to the fact that you should not edit any files as all the config options are in DB.

**Comment by cataalin** [comment]
I was saying it because I tried an autoban and nothing comes out, but what about this image? when does it appear? "Your IP is not banned"

> ![image](https://user-images.githubusercontent.com/7156344/46217888-85370200-c343-11e8-8523-be077ef74e12.png) I guess the bans page is complete. Finishing the viewer now!

**Comment by Wruczek** [comment]
It seems that it was removed, only the "You are banned" alert exists.

**Comment by cataalin** [comment]
> 

ah I understand, that's why there is no div in body.latte, okay thanks I'll close the topic.

**Comment by cataalin** [comment]
> It seems that it was removed, only the "You are banned" alert exists.

I have tried to self-ban, and the alert does not appear, should it appear?

![fdffffffffffff](https://user-images.githubusercontent.com/28767431/207469636-d5f2dcd9-3349-4ce7-95a0-4350b7e21d1e.jpg)

**Comment by Wruczek** [comment]
It should - check if the banned IP is the same as shown in the login modal screen when hovering over the 𝝅 icon.

**Comment by cataalin** [comment]
> It should - check if the banned IP is the same as shown in the login modal screen when hovering over the 𝝅 icon.



I have checked and it is the same.

**Comment by Wruczek** [comment]
Can you attach a screenshot both from the  𝝅 icon and banlist? You can censor half of the IP.
Also, are any other files modified? Please make sure you are using TS-website with no file modifications.

**Comment by cataalin** [comment]
> ¿Puedes adjuntar una captura de pantalla tanto del ícono 𝝅 como de la lista de prohibición? Puedes censurar la mitad de la IP. Además, ¿se modifican otros archivos? Asegúrese de estar utilizando el sitio web de TS sin modificaciones de archivos.


original website without any editing, it shows the same ip check, I have php 7.4 and use https protocol

![fffffffffddddddddddddddd](https://user-images.githubusercontent.com/28767431/207471111-ea475eb2-67c3-417f-98bf-5baf163cc7b3.jpg)

**Comment by Wruczek** [comment]
Edit `bans.php` and add the following line on line 63
```diff
if ($ip === Utils::getClientIp()) {
    $ipbanned = [
        "invoker" => (string) $ban["invokername"],
        "reason" => (string) $ban["reason"]
    ];

+   var_dump($ipbanned);
}
```

Refresh the website, you should see additional text show up - please screenshot or copy/paste it here.

**Comment by cataalin** [comment]
> Edit `bans.php` and add the following line on line 63
> 
> ```diff
> if ($ip === Utils::getClientIp()) {
>     $ipbanned = [
>         "invoker" => (string) $ban["invokername"],
>         "reason" => (string) $ban["reason"]
>     ];
> 
> +   var_dump($ipbanned);
> }
> ```
> 
> Refresh the website, you should see additional text show up - please screenshot or copy/paste it here.



It matches me on line 53 and nothing appears, it does not show the var_dump

**Comment by Wruczek** [comment]
Move it after the if statement + add an echo with more info:
```diff
  if ($ip === Utils::getClientIp()) {
      $ipbanned = [
          "invoker" => (string) $ban["invokername"],
          "reason" => (string) $ban["reason"]
      ];
  }

+ var_dump($ipbanned);
+ echo "IP: $ip, Client: " . Utils::getClientIp() . "<br>\n";
```

**Comment by cataalin** [comment]
> Move it after the if statement + add an echo with more info:
> 
> ```diff
>   if ($ip === Utils::getClientIp()) {
>       $ipbanned = [
>           "invoker" => (string) $ban["invokername"],
>           "reason" => (string) $ban["reason"]
>       ];
>   }
> 
> + var_dump($ipbanned);
> + echo "IP: $ip, Client: " . Utils::getClientIp() . "<br>\n";
> ```

now show me

`bool(false) IP: 47.63.***.***, Client: 47.63.***.***`

**Comment by Wruczek** [comment]
Those two strings must somehow be different, can you send the uncensored version via email to ![image](https://user-images.githubusercontent.com/7156344/207473124-b096bc63-841e-4ec9-8fc6-933a96b7c0b5.png)?

**Comment by cataalin** [comment]
> Those two strings must somehow be different, can you send the uncensored version via email to ![image](https://user-images.githubusercontent.com/7156344/207473124-b096bc63-841e-4ec9-8fc6-933a96b7c0b5.png)?

sure, tell me what you need me to send you exactly

**Comment by Wruczek** [comment]
Send the same output but not censored.

**Comment by cataalin** [comment]
> Send the same output but not censored.

sent, you can check.

**Comment by Wruczek** [comment]
I see, it compares against the censored IP....

Try changing [these lines](https://github.com/Wruczek/ts-website/blob/2.0/src/bans.php#L47-L55) to:
```php
    try {
        $ipCensored = Utils::censorIpAddress($ip);
    } catch (\Exception $e) {}

    if ($lastNickname !== null) {
        $abbreviation = [$ipCensored, "IP"];
    } else {
        $target = $ipCensored;
    }
```

**Comment by cataalin** [comment]
> I see, it compares against the censored IP....
> 
> Try changing [these lines](https://github.com/Wruczek/ts-website/blob/2.0/src/bans.php#L47-L55) to:
> 
> ```
>     try {
>         $ipCensored = Utils::censorIpAddress($ip);
>     } catch (\Exception $e) {}
> 
>     if ($lastNickname !== null) {
>         $abbreviation = [$ipCensored, "IP"];
>     } else {
>         $target = $ipCensored;
>     }
> ```

It seems to work, thank you very much for the help, there are a couple of other similar things that I'm trying to solve but I don't know if I should open a topic for each one, what do you think, would you have time?

![fdsfdshhgf](https://user-images.githubusercontent.com/28767431/207475736-320037fc-4bd0-46eb-83f1-65d3dcf3df2f.jpg)

**Comment by Wruczek** [comment]
Yes, each problem should have its own issue.

**Comment by cataalin** [comment]
> Yes, each problem should have its own issue.

Ok, I was saying it so as not to make you too dizzy, I have been able to solve some things but there are some that I can't find with it, when I have time I'll tell you, thanks!
