### ISSUE TITLE
news and language link

### ISSUE THREAD

**Issue by cataalin** [Wruczek/ts-website#217]
I'm testing the link option in the news but if you activate it, it redirects you to `news.php?id=$newsId` but there is no php file for this option, is it still working? [DefaultNewsStore.php](https://github.com/Wruczek/ts-website/blob/4ac20a09f700c5da8763387b22010dbb260008f1/src/private/php/News/DefaultNewsStore.php#L49)

the `langid` of the DB news doesn't work either, it should show the news for the assigned id I guess right?

**Comment by toster234** [comment]
Both options are not completed.

**Comment by cataalin** [comment]
> Both options are not completed.

ah okey, thanks
