### ISSUE TITLE
Brak statusu js

### ISSUE THREAD

**Issue by skip850** [Wruczek/ts-website#22]
Strona nie może wczytać statusu serwera. Tak się stało po aktualizacji strony z 1.3.1 na 1.3.7
![chrome_2017-01-21_17-58-21](https://cloud.githubusercontent.com/assets/13948709/22176119/5363209e-e003-11e6-9549-cc590bc04e35.png)

**Comment by Wruczek** [comment]
Podaj proszę odpowiedź z API `/api/status.php`

**Comment by skip850** [comment]
`{"success":false,"id":"script_error","message":"There has been an error while retrieving the server status","error":"[\/var\/www\/clients\/client1\/web1\/web\/lib\/phpfastcache\/phpFastCache\/Core\/phpFastCache.php @ 166] is_writable(): open_basedir restriction in effect. File(\/var\/www\/ecounter.pl\/web\/..\/) is not within the allowed path(s): (\/var\/www\/clients\/client1\/web1\/web:\/var\/www\/clients\/client1\/web1\/private:\/var\/www\/clients\/client1\/web1\/tmp:\/var\/www\/xxx.pl\/web:\/srv\/www\/xxx.pl\/web:\/usr\/share\/php5:\/usr\/share\/php:\/tmp:\/usr\/share\/phpmyadmin:\/etc\/phpmyadmin:\/var\/lib\/phpmyadmin)"}`

Widocznie problem leży po mojej stronie.

**Comment by Wruczek** [comment]
Musisz zapewnić dostęp zapisu do folderu dla `phpfastcache`
