### ISSUE TITLE
Design error

### ISSUE THREAD

**Issue by Justman100** [Wruczek/ts-website#222]
I have pulled from both repo direct and releases, but my instance always looks like this:

![grafik](https://github.com/Wruczek/ts-website/assets/149507651/cc50a71e-b55f-4a04-9404-27c41136654f)

**Comment by Justman100** [comment]
@Wruczek

**Comment by Wruczek** [comment]
Please stop tagging me on every single open issue.
Can you link your website?

**Comment by Justman100** [comment]
> Please stop tagging me on every single open issue.

Ja, sorry! Es schien jedoch so, als wärst du inaktiv!
<br>
> Can you link your website?

[Here](https://ts.justman10000.de/)

**Comment by Wruczek** [comment]
Your theme stylesheet is missing: https://ts.justman10000.de/css/themes/dark.css

**Comment by Justman100** [comment]
> Your theme stylesheet is missing: https://ts.justman10000.de/css/themes/dark.css

Okay, I've fixed it!
