### ISSUE TITLE
Color change for Serverstatus

### ISSUE THREAD

**Issue by TheChaosToast** [Wruczek/ts-website#224]
Hello everyone,

I would like to change the design a bit. Specifically, the “background color” of the server status. (online, online record, etc.) I don’t think this “red” is nice ;). And I want to change the online status of the admins when they are online. Where can I find the CSS file and which section of the CSS is responsible for it?
Unfortunately I didn't find it. Thank you!

**Comment by cataalin** [comment]
> Hello everyone,
> 
> I would like to change the design a bit. Specifically, the “background color” of the server status. (online, online record, etc.) I don’t think this “red” is nice ;). And I want to change the online status of the admins when they are online. Where can I find the CSS file and which section of the CSS is responsible for it? Unfortunately I didn't find it. Thank you!

The location of the CSS is in these routes, there you can change what you are looking for.

```
css/style.css
css/themes/dark.css
```

```
.server-status .data .badge
```

**Comment by TheChaosToast** [comment]
Thanks so much. it works perfect!
