### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by kisiolpl** [Wruczek/ts-website#225]
[Mon May 20 07:09:28.360846 2024] [php7:error] [pid 16855] [client 81.207.196.49:54690] PHP Fatal error:  Uncaught Exception: iconid need to be an int or numeric string in /var/www/html/private/php/ServerIconCache.php:20\nStack trace:\n#0 /var/www/html/private/php/ServerIconCache.php(34): Wruczek\\TSWebsite\\ServerIconCache::getIconBytes()\n#1 /var/www/html/private/php/ServerIconCache.php(46): Wruczek\\TSWebsite\\ServerIconCache::hasIcon()\n#2 /var/www/html/private/php/ServerIconCache.php(72): Wruczek\\TSWebsite\\ServerIconCache::syncIcons()\n#3 /var/www/html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(201): Wruczek\\TSWebsite\\ServerIconCache::Wruczek\\TSWebsite\\{closure}()\n#4 /var/www/html/private/php/ServerIconCache.php(74): Wruczek\\PhpFileCache\\PhpFileCache->refreshIfExpired()\n#5 /var/www/html/private/php/load.php(96): Wruczek\\TSWebsite\\ServerIconCache::syncIfNeeded()\n#6 /var/www/html/index.php(6): require_once('/var/www/html/p...')\n#7 {main}\n  thrown in /var/www/html/private/php/ServerIconCache.php on line 20

**Comment by cataalin** [comment]
> [Mon May 20 07:09:28.360846 2024] [php7:error] [pid 16855] [client 81.207.196.49:54690] PHP Fatal error: Uncaught Exception: iconid need to be an int or numeric string in /var/www/html/private/php/ServerIconCache.php:20\nStack trace:\n#0 /var/www/html/private/php/ServerIconCache.php(34): Wruczek\TSWebsite\ServerIconCache::getIconBytes()\n#1 /var/www/html/private/php/ServerIconCache.php(46): Wruczek\TSWebsite\ServerIconCache::hasIcon()\n#2 /var/www/html/private/php/ServerIconCache.php(72): Wruczek\TSWebsite\ServerIconCache::syncIcons()\n#3 /var/www/html/private/vendor/wruczek/php-file-cache/src/PhpFileCache.php(201): Wruczek\TSWebsite\ServerIconCache::Wruczek\TSWebsite\{closure}()\n#4 /var/www/html/private/php/ServerIconCache.php(74): Wruczek\PhpFileCache\PhpFileCache->refreshIfExpired()\n#5 /var/www/html/private/php/load.php(96): Wruczek\TSWebsite\ServerIconCache::syncIfNeeded()\n#6 /var/www/html/index.php(6): require_once('/var/www/html/p...')\n#7 {main}\n thrown in /var/www/html/private/php/ServerIconCache.php on line 20

The issue you're encountering involves a PHP fatal error that arises from the ServerIconCache.php script. The error message indicates that there is an unhandled exception because the iconid variable needs to be either an integer or a numeric string, but it is not, check the error lines in the PHP, or replace it with the original if you modified it, also delete the icon cache folder so that it is generated again.

**Comment by Wruczek** [comment]
Debugged the issue with the user, it turned out that an icon file with invalid name ("something.png" instead of "icon_1234567") existed in TS3 server icon directory. It was uploaded manually by the user.
