### ISSUE TITLE
Font awesome in News Title?

### ISSUE THREAD

**Issue by TheChaosToast** [Wruczek/ts-website#228]
Hello everyone,

is there a way to insert font awesome into the news title? So in the headline? I've currently solved it using unicode, but it would be nice if you could do it with font awesome.

if so, how?

many thanks <3

**Comment by cataalin** [comment]
> Hello everyone,
> 
> is there a way to insert font awesome into the news title? So in the headline? I've currently solved it using unicode, but it would be nice if you could do it with font awesome.
> 
> if so, how?
> 
> many thanks <3

```
Src/private/templates/index.latte
```
You already have font awesome loaded, you just need to add it, you have an example by opening the index.latte on line 7, add it on line 28 for example and leave it to your liking. 
```
<i class="far fa-newspaper"></i>
```

**Comment by TheChaosToast** [comment]
Hello Catalin,

I meant it differently: When I add new news entries to the database, I can enter the title and the content. And I would like to use Font Awesome for the title, unfortunately that doesn't work, or my approach is wrong. Otherwise I'll stick with Unicode if that's too complicated.

<3

**Comment by cataalin** [comment]
> Hello Catalin,
> 
> I meant it differently: When I add new news entries to the database, I can enter the title and the content. And I would like to use Font Awesome for the title, unfortunately that doesn't work, or my approach is wrong. Otherwise I'll stick with Unicode if that's too complicated.
> 
> <3

Do you mean using font awesome as if it were icons in the text?

**Comment by TheChaosToast** [comment]
Yes, that's what I mean.

**Comment by cataalin** [comment]
> Yes, that's what I mean.

If you write the news manually in the db, put the icon in the db in this way, for example: 

```
<i class="fas fa-star"></i> test tittle for news
``` 

and then to show it both in the title and in the news that shows the icon, use the noescape filter, for example like this in index.latte: 

```
{$news["title"]}
``` 

Change to: 

```
{$news["title"]|noescape}
```

**Comment by TheChaosToast** [comment]
> If you write the news manually in the db, put the icon in the db in this way, for example:
> 
> ```
> <i class="fas fa-star"></i> test tittle for news
> ```
> 
> and then to show it both in the title and in the news that shows the icon, use the noescape filter, for example like this in index.latte:
> 
> ```
> {$news["title"]}
> ```
> 
> Change to:
> 
> ```
> {$news["title"]|noescape}
> ```

hello cataalin,

that's exactly what I wanted. thank you so much <3

**Comment by Wruczek** [comment]
I've also updated TS-website to not escape news titles :)

**Comment by TheChaosToast** [comment]
I have to report again:

I have now saved a second and third news entry in my database. The first is displayed with an icon, the second and third are no longer displayed.

At first I thought I had entered it incorrectly, but it seems to be correct.

**Comment by Wruczek** [comment]
Only the first news entry is displayed?

**Comment by TheChaosToast** [comment]
Yes.

**Comment by Wruczek** [comment]
Probably the HTML used in the title is invalid. Can you screenshot or dump the news table contents with titles of all news fully visible?

**Comment by TheChaosToast** [comment]
sure,

I hope that's what you meant 😀
![Screenshot_20240709_070800_Samsung Internet](https://github.com/Wruczek/ts-website/assets/36563709/974ecfa5-4ffa-4e3e-8f14-46ed022df32d)
![Screenshot_20240709_070918_Samsung Internet](https://github.com/Wruczek/ts-website/assets/36563709/5df2e176-60d5-49a2-bf4d-a3e0466491d1)
![Screenshot_20240709_071001_Samsung Internet](https://github.com/Wruczek/ts-website/assets/36563709/ba4a382d-a128-42b2-9902-aef4043e120a)

**Comment by Wruczek** [comment]
I've tested the same title without issues. I assume that your news content has invalid HTML tags that breaks the site.
![image](https://github.com/Wruczek/ts-website/assets/7156344/2e4bc347-e40b-4801-a102-d632b69e1fab)

**Comment by TheChaosToast** [comment]
I'm wondering where I changed the HTML tags? The only thing I changed was adding a meta description.

**Comment by Wruczek** [comment]
Can you dump the news table in DB and attach it here?

**Comment by TheChaosToast** [comment]
Here:

Pls delete this file after Download here

**Comment by Wruczek** [comment]
Works for me. Maybe try undoing your modifications by replacing your files with the ones from the repo - for example, replace index.latte [with the original file](https://github.com/Wruczek/ts-website/blob/2.0/src/private/templates/index.latte)

![image](https://github.com/Wruczek/ts-website/assets/7156344/e07e5bf1-d4dd-40a7-861c-73c4311ff87c)

**Comment by TheChaosToast** [comment]
damn, unfortunately it's not the index.latte that's the problem. I replaced the file and deleted the cache. Unfortunately, the awesome font isn't displayed in the test :(

**Comment by TheChaosToast** [comment]
hello wruczek,

it's been resolved. for some reason it's working again now. I restarted the web server this morning, maybe that was the problem.

thank you for your help and support
