### ISSUE TITLE
Server Status bugged?

### ISSUE THREAD

**Issue by todworgen** [Wruczek/ts-website#25]
I tryed your site ^^ it is really amazing but i have a Problem with the TS3 Server Status: It just says error
i tried already the ip the Domain and localhost: every time only error but i can connect to my server

**Comment by Wruczek** [comment]
Are other parts of the website working? For example, the viewer?

**Comment by todworgen** [comment]
Yes they are

**Comment by Wruczek** [comment]
Can you post your config file? Remember to blank the password.

**Comment by todworgen** [comment]
<?php
/*
    Author: Wruczek
    Donate: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9PL5J7ULZQYJQ

    I am happy to take any programming-related requests, add additional features or modify the code to suit your needs for a small donation :)
    I am experienced at Java, PHP, HTML, CSS, Javascript, SQL, server configurations ect.
    For business enquiries only: wruczekk at gmail.com, for anything else please join Telegram chat.


    Need help? Join our telegram group for news, announcements, help and general chat about ts-website: https://telegram.me/tswebsite
*/



/************* General configuration *************/

$config["general"]["title"]         = "Shadowslayer.eu";                                 // Website title - displayed in the menu
$config["general"]["icon"]          = "img/icon/icon-32.png";                       // Website icon
$config["general"]["subtitle"]      = " - Best TeamSpeak server!";                  // Website subtitle
$config["general"]["desc"]          = "Polski serwer TeamSpeak! Zapraszamy :)";     // Website description - displayed in Google search engine
$config["general"]["newsDir"]       = "config/news";                                // News folder (relative to project folder)
$config["general"]["timezone"]      = "Europe/Warsaw";                              // Your timezone - http://php.net/manual/en/timezones.php
$config["general"]["christmasmode"] = false;                                         // Set to false to permanently disable christmas mode activated in December

$config["general"]["enablehta"]     = true; // Enable / Disable additional website features (recommended, but
                                             // you need to have up-to-date version of Apache and install mod_rewrite)
                                             // After setting to true, go into .htaccess file and uncomment 19 line


/********* TeamSpeak configuration *********/

$config['teamspeak']['host']          = 'localhost';          // TeamSpeak host address
$config['teamspeak']['login']         = 'serveradmin';        // Login
$config['teamspeak']['password']      = 'hK63BmAb';           // Password
$config['teamspeak']['server_port']   = 9987;                 // TeamSpeak server port
$config['teamspeak']['query_port']    = 10011;                // Query port
$config['teamspeak']['displayip']     = 'voice.shadowslayer.eu';       // IP shown to users and used for connections



/************* Additional navigation links - you can link to your stuff *************/

// TEMPLATE: (ICON is an icon name from: http://fontawesome.io/icons/)
// $config["navlinks"][] = ["icon", "displayed text", "link"];

$config["navlinks"][] = ["fa-facebook-official", "Facebook", "https://facebook.com/Facebook"];
$config["navlinks"][] = ["fa-twitter-square", "Twitter", "https://twitter.com/Twitter"];
$config["navlinks"][] = ["fa-comments", "Forum", "forum"];



/************* Adminlist configuration *************/

// ID of servergroups displayed as admins in Adminlist. Put it in the same way you want it to be displayed.
$config["adminlist"] = [9, 14, 15];



/************* Contact panel configuration *************/

$config['contact']['title'] = 'Kontaktiere uns';

/*
TIP: You can remove all items below to hide contact panel

CONTACT PANEL SYNTAX:
$config['contact']['items'][] = ["name", "link description", "link"];

FOR EXAMPLE:
$config['contact']['items'][] = ["Telegram", "@Wruczek", "https://telegram.me/Wruczek"];
*/

$config['contact']['items'][] = ["TeamSpeak", "Support channel", "ts3server://teamspeakip?cid=30"];
$config['contact']['items'][] = ["Email", "contact@email.com", "mailto:contact@email.com"];
$config['contact']['items'][] = ["Telegram", "@Telegram", "https://telegram.me/Telegram"];
$config['contact']['items'][] = ["Twitter", "@Twitter", "https://twitter.com/Twitter"];
<?php
/*
    Author: Wruczek
    Donate: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9PL5J7ULZQYJQ

    I am happy to take any programming-related requests, add additional features or modify the code to suit your needs for a small donation :)
    I am experienced at Java, PHP, HTML, CSS, Javascript, SQL, server configurations ect.
    For business enquiries only: wruczekk at gmail.com, for anything else please join Telegram chat.


    Need help? Join our telegram group for news, announcements, help and general chat about ts-website: https://telegram.me/tswebsite
*/



/************* General configuration *************/

$config["general"]["title"]         = "Shadowslayer.eu";                                 // Website title - displayed in the menu
$config["general"]["icon"]          = "img/icon/icon-32.png";                       // Website icon
$config["general"]["subtitle"]      = " - Best TeamSpeak server!";                  // Website subtitle
$config["general"]["desc"]          = "Polski serwer TeamSpeak! Zapraszamy :)";     // Website description - displayed in Google search engine
$config["general"]["newsDir"]       = "config/news";                                // News folder (relative to project folder)
$config["general"]["timezone"]      = "Europe/Warsaw";                              // Your timezone - http://php.net/manual/en/timezones.php
$config["general"]["christmasmode"] = false;                                         // Set to false to permanently disable christmas mode activated in December

$config["general"]["enablehta"]     = true; // Enable / Disable additional website features (recommended, but
                                             // you need to have up-to-date version of Apache and install mod_rewrite)
                                             // After setting to true, go into .htaccess file and uncomment 19 line


/********* TeamSpeak configuration *********/

$config['teamspeak']['host']          = '"It tried IP adress , Domain and Localhost';          // TeamSpeak host address
$config['teamspeak']['login']         = 'serveradmin';        // Login
$config['teamspeak']['password']      = '"Here was my Password"';           // Password
$config['teamspeak']['server_port']   = 9987;                 // TeamSpeak server port
$config['teamspeak']['query_port']    = 10011;                // Query port
$config['teamspeak']['displayip']     = 'voice.shadowslayer.eu';       // IP shown to users and used for connections



/************* Additional navigation links - you can link to your stuff *************/

// TEMPLATE: (ICON is an icon name from: http://fontawesome.io/icons/)
// $config["navlinks"][] = ["icon", "displayed text", "link"];

$config["navlinks"][] = ["fa-facebook-official", "Facebook", "https://facebook.com/Facebook"];
$config["navlinks"][] = ["fa-twitter-square", "Twitter", "https://twitter.com/Twitter"];
$config["navlinks"][] = ["fa-comments", "Forum", "forum"];



/************* Adminlist configuration *************/

// ID of servergroups displayed as admins in Adminlist. Put it in the same way you want it to be displayed.
$config["adminlist"] = [9, 14, 15];



/************* Contact panel configuration *************/

$config['contact']['title'] = 'Kontaktiere uns';

/*
TIP: You can remove all items below to hide contact panel

CONTACT PANEL SYNTAX:
$config['contact']['items'][] = ["name", "link description", "link"];

FOR EXAMPLE:
$config['contact']['items'][] = ["Telegram", "@Wruczek", "https://telegram.me/Wruczek"];
*/

$config['contact']['items'][] = ["TeamSpeak", "Support channel", "ts3server://teamspeakip?cid=30"];
$config['contact']['items'][] = ["Email", "contact@email.com", "mailto:contact@email.com"];
$config['contact']['items'][] = ["Telegram", "@Telegram", "https://telegram.me/Telegram"];
$config['contact']['items'][] = ["Twitter", "@Twitter", "https://twitter.com/Twitter"];

**Comment by todworgen** [comment]
```
<?php
/*
    Author: Wruczek
    Donate: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9PL5J7ULZQYJQ

    I am happy to take any programming-related requests, add additional features or modify the code to suit your needs for a small donation :)
    I am experienced at Java, PHP, HTML, CSS, Javascript, SQL, server configurations ect.
    For business enquiries only: wruczekk at gmail.com, for anything else please join Telegram chat.


    Need help? Join our telegram group for news, announcements, help and general chat about ts-website: https://telegram.me/tswebsite
*/



/************* General configuration *************/

$config["general"]["title"]         = "Shadowslayer.eu";                                 // Website title - displayed in the menu
$config["general"]["icon"]          = "img/icon/icon-32.png";                       // Website icon
$config["general"]["subtitle"]      = " - Best TeamSpeak server!";                  // Website subtitle
$config["general"]["desc"]          = "Polski serwer TeamSpeak! Zapraszamy :)";     // Website description - displayed in Google search engine
$config["general"]["newsDir"]       = "config/news";                                // News folder (relative to project folder)
$config["general"]["timezone"]      = "Europe/Warsaw";                              // Your timezone - http://php.net/manual/en/timezones.php
$config["general"]["christmasmode"] = false;                                         // Set to false to permanently disable christmas mode activated in December

$config["general"]["enablehta"]     = true; // Enable / Disable additional website features (recommended, but
                                             // you need to have up-to-date version of Apache and install mod_rewrite)
                                             // After setting to true, go into .htaccess file and uncomment 19 line


/********* TeamSpeak configuration *********/

$config['teamspeak']['host']          = '"I tried localhost, IP  and Domain"';          // TeamSpeak host address
$config['teamspeak']['login']         = 'serveradmin';        // Login
$config['teamspeak']['password']      = '"Here was my Password"';           // Password
$config['teamspeak']['server_port']   = 9987;                 // TeamSpeak server port
$config['teamspeak']['query_port']    = 10011;                // Query port
$config['teamspeak']['displayip']     = '"Here was my Display ip"';       // IP shown to users and used for connections



/************* Additional navigation links - you can link to your stuff *************/

// TEMPLATE: (ICON is an icon name from: http://fontawesome.io/icons/)
// $config["navlinks"][] = ["icon", "displayed text", "link"];

$config["navlinks"][] = ["fa-facebook-official", "Facebook", "https://facebook.com/Facebook"];
$config["navlinks"][] = ["fa-twitter-square", "Twitter", "https://twitter.com/Twitter"];
$config["navlinks"][] = ["fa-comments", "Forum", "forum"];



/************* Adminlist configuration *************/

// ID of servergroups displayed as admins in Adminlist. Put it in the same way you want it to be displayed.
$config["adminlist"] = [9, 14, 15];



/************* Contact panel configuration *************/

$config['contact']['title'] = 'Kontaktiere uns';

/*
TIP: You can remove all items below to hide contact panel

CONTACT PANEL SYNTAX:
$config['contact']['items'][] = ["name", "link description", "link"];

FOR EXAMPLE:
$config['contact']['items'][] = ["Telegram", "@Wruczek", "https://telegram.me/Wruczek"];
*/

$config['contact']['items'][] = ["TeamSpeak", "Support channel", "ts3server://teamspeakip?cid=30"];
$config['contact']['items'][] = ["Email", "contact@email.com", "mailto:contact@email.com"];
$config['contact']['items'][] = ["Telegram", "@Telegram", "https://telegram.me/Telegram"];
$config['contact']['items'][] = ["Twitter", "@Twitter", "https://twitter.com/Twitter"];

```

**Comment by Wruczek** [comment]
`$config["general"]["enablehta"] = true;` Do you have propertly configured server for that? Mod rewrite, htaccess support, ect. If not, please set it back to false.

**Comment by todworgen** [comment]
# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#
AccessFileName .htaccess

#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>

**Comment by todworgen** [comment]
Sorry forgot the Code marks in markdown .-.

**Comment by todworgen** [comment]
And my Server say when i try rewrite 

> sudo a2enmod rewrite && sudo service apache2 restart
Module rewrite already enabled

**Comment by Wruczek** [comment]
You don't have enabled support for configuration file rewriting

https://github.com/Wruczek/ts-website/wiki/Website-Installation#recommended-web-server-configuration
http://stackoverflow.com/a/22526144

**Comment by todworgen** [comment]
I changed the needed Thing in the config of Apache restarted it and i get error to.

**Comment by todworgen** [comment]
Okay forgett it
I found the mistake it was from Apache2 it didnt restart when i wrote service Apache 2 restart i had to reboot my server

**Comment by todworgen** [comment]
So thanks for the help wruczek  ^^

**Comment by Wruczek** [comment]
Glad to hear it!

**Comment by saadblaoui** [comment]
the ts-website don't send a confirmation code :(

**Comment by Wruczek** [comment]
@saadblaoui wrong issue + the solution for it is [already planned](https://github.com/Wruczek/ts-website/projects/1#card-16068499)
