### ISSUE TITLE
banlist bugged.

### ISSUE THREAD

**Issue by MikkelDK** [Wruczek/ts-website#3]
Hello.

if i ban meself with 2 minutes (i never show up) on the banlist.
Are it's an bug? bcs there is nothing.

**Comment by Wruczek** [comment]
The banlist is cached for 10 minutes.
This means that banlist is refreshed and downloaded from the server one time and then saved for 10 minutes. This is so we dont need to load it every time user refreshes the website.

You can change it in ``bans.php`` at line 21. "600" is the number of seconds. (600 seconds = 10 minutes)

**Comment by MikkelDK** [comment]
Oooh. nice! thanks for info! ;) i was like: Why it didnt show up :D
