### ISSUE TITLE
Facebook Open Graph Tags

### ISSUE THREAD

**Issue by OlcayDmryrk** [Wruczek/ts-website#31]
Where should i place the open graph tags? (Sorry, my English is very bad.)

**Comment by Wruczek** [comment]
If you are talking about [Open Graph meta tags](https://developers.facebook.com/docs/sharing/webmasters), you can put them into `include/header.php` file, between lines `21` and `23` and then test the result in a [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/).

This is how the meta tags should look like:
![image](https://cloud.githubusercontent.com/assets/7156344/24805430/0d5c9158-1bb2-11e7-87e0-053bd1aac677.png)

**Comment by Wruczek** [comment]
No response from reporter, closing.
