### ISSUE TITLE
Sidebox

### ISSUE THREAD

**Issue by Drooz** [Wruczek/ts-website#33]
Is it possible to edit AND add new sidebox. I want to use it as a simple no-db CMS😁

**Comment by Wruczek** [comment]
Yes! You can copy and paste [these lines](https://github.com/Wruczek/ts-website/blob/master/include/header.php#L145-L150) in `include/header.php` file.

Then replace everything inside `panel-heading` to change your title, and everything in `panel-body` to change the panel content. Also, remove the class `adminlist` as this panel no longer serves as a adminlist.

**Comment by Wruczek** [comment]
No response from reporter, closing.

**Comment by Drooz** [comment]
Sorry I got via email I was not able to respond thank you
