### ISSUE TITLE
How to change the colors?

### ISSUE THREAD

**Issue by xdpg66** [Wruczek/ts-website#35]
It is about changing the colors of the selected:

<img src="http://i.imgur.com/qvzmRnN.png" />

**Comment by Wruczek** [comment]
You can change the colors in [theme.css](https://github.com/Wruczek/ts-website/blob/master/css/theme.css) file.

**Comment by xdpg66** [comment]
I edited and nothing

**Comment by Wruczek** [comment]
Try refreshing the website using CTRL + F5

**Comment by xdpg66** [comment]
Thank you :)
