### ISSUE TITLE
idea/tip needed

### ISSUE THREAD

**Issue by MikkelDK** [Wruczek/ts-website#4]
Are there some "easy way" to edit rules.md / add news via .md (it's looks like etc github)

could be nice with an "admin panel" for edit rules/add + edit/delete/add news.

**Comment by Wruczek** [comment]
I plan on making a simple admin panel, but currently dont have time for it.
Its a lot of work, this idea needs additional SQL database, and everything needs to be super secure (prevent sqlinjection ect.). But I plan on doing that using [AdminLTE 2](https://almsaeedstudio.com/themes/AdminLTE/index.html) template.

Currently you can help yourself by using [extensions for your IDE](https://github.com/gruehle/MarkdownPreview) or [desktop markdown editors](http://markdownpad.com/).
