### ISSUE TITLE
[Suggestion] Small detail

### ISSUE THREAD

**Issue by toster234** [Wruczek/ts-website#42]
If this is a worldwide project, why alt in site logo is in polish ? :P 
`<a class="navbar-brand" href="."><img style="width: 64px;" src="img/icon/icon-64.png" alt="Logo strony"><?php echo $config["general"]["title"]; ?></a>`

Should be:
`<a class="navbar-brand" href="."><img style="width: 64px;" src="img/icon/icon-64.png" alt="Site logo"><?php echo $config["general"]["title"]; ?></a>`

Such a small detail.

**Comment by Wruczek** [comment]
The first versions was in polish, later I translated it into other languages. still, there are some small leftovers in the code :D Im not gonna change it, I don't think its important as the whole codebase will be rewritten in 2.0
