### ISSUE TITLE
[Suggestion] Parsing phpBB news to ts-website index

### ISSUE THREAD

**Issue by bykidi** [Wruczek/ts-website#43]
config.php

$config['newsimport']['forumurl']   = testforum.com/forum;                 // 
$config['newsimport']['subforumid']    = 1;                // 
$config['newsimport']['amountofnewstoimport']     = '5';       // Last %amountofnewstoimport% news will be shown on index page from subforum id %subforumid%

**Comment by Wruczek** [comment]
Similar thing with news and rss feed is already planned for ts-website 2.0, see #36. Using rss feed you will be able to integrate with mybb as well ;)

> New news system, fetching feed from Facebook, Twitter or other websites using rss-bridge

**Comment by bykidi** [comment]
Wow... G R E A T!
