### ISSUE TITLE
[Suggestion] Custom AFK message in Adminlist

### ISSUE THREAD

**Issue by bykidi** [Wruczek/ts-website#44]
![default](https://cloud.githubusercontent.com/assets/1337953/25773512/491fef28-3287-11e7-8247-98b1c8da512c.png)
![default](https://cloud.githubusercontent.com/assets/1337953/25773521/59a66d54-3287-11e7-9a34-1538f517a3cd.png)
How sweet is that? Can you do that in 2.0? Please? 💯  💯  💯

**Comment by toster234** [comment]
It was nice :100:

**Comment by Wruczek** [comment]
Great idea! Definitely adding to 2.0. Thanks for suggestion!

**Comment by derrobin154** [comment]
I have added your Suggestion with the new Pull Request.
https://github.com/Wruczek/ts-website/pull/80

Now i wait for accepting.
