### ISSUE TITLE
server status infinite load

### ISSUE THREAD

**Issue by MojoW045** [Wruczek/ts-website#45]
Since i have migrated my web/teamspeak server to a different cloud host my server status has been loading forever but not showing.
The rest of the site is working normally but only server status is doing that.
Do you know what can cause this ?

Thanks

**Comment by Wruczek** [comment]
If you are using Chrome / Firefox, open Developer Tools (F12) and click on tab "Console". What error do you see?

**Comment by MojoW045** [comment]
TypeError: json is undefined[More info]  status.js:1:198
	success https://ts3.solidsn4ke.com/js/status.js:1:198
	i https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27146
	fireWith https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27914
	z https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:4:12057
	c/< https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:4:15619
	onStopRequest

**Comment by MojoW045** [comment]
And this is what chrome says:

status.js:1 Uncaught TypeError: Cannot read property 'success' of undefined
    at Object.success (status.js:1)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)

**Comment by Wruczek** [comment]
Looks like website dont have permissions to save in the cache folder. Try chmod 775 your cache folder.

**Comment by MojoW045** [comment]
That was it thank you.
I did not do it recursive the first time
