### ISSUE TITLE
[Suggestion] Paginacja/Stronicowanie wiadomości

### ISSUE THREAD

**Issue by toster234** [Wruczek/ts-website#50]
Lepiej chyba by było jeśli na jednej stronie było by np po 3 wiadomości niż jedna długa strona :)

Przykład:
![image](https://cloud.githubusercontent.com/assets/26941529/26584575/895cb6fa-4549-11e7-851c-a3b74cab2620.png)

**Comment by Wruczek** [comment]
Będzie wraz z updatem systemu wiadomości w 2.0

PS. Pisz po angielsku...

**Comment by toster234** [comment]
Pisałem specjalnie po polsku byś mnie zrozumiał XDD

**Comment by Wruczek** [comment]
Dodane w ts-website 2.0

**Comment by avsaponchik** [comment]
@Wruczek v2.0 HYPE?
Lang files?
etc etc

**Comment by Wruczek** [comment]
I will be posting updates asap on the telegram group, maybe even closed beta soon :D
