### ISSUE TITLE
Question: Discord Website

### ISSUE THREAD

**Issue by AntoninHuaut** [Wruczek/ts-website#52]
A version of ts-website for Discord is planned ?

**Comment by Wruczek** [comment]
Great question. I will think about adding Discord support to ts-website 3.0. I need some more time and make myself familiar with Discord itself.

**Comment by AntoninHuaut** [comment]
Discord has a very good API :D

**Comment by Wruczek** [comment]
Yeah, but I need to get myself more familiar with the Discord itself :D For example, I need to check if Discord have (and allows to get) the same functions as TeamSpeak. Naming is also a problem because then it will no longer be a "ts-webiste".

**Comment by Wruczek** [comment]
Changing from "enchantment" to "postponed", so I can think about this later around the release of ts-website 3.0

**Comment by derrobin154** [comment]
Hello,
In Cooperation with Wruczek, i will build a Discord-Website on the Base System from ts-website.
I think i releasing it bevor December 17.

Greetings!

**Comment by Wruczek** [comment]
\* Please note that I'm not associated with discord-website, It's a independent fork of ts-website

**Comment by Wruczek** [comment]
Closing as there are no plans for "Discord-website" in a near future.
