### ISSUE TITLE
Obvious files in cache folder

### ISSUE THREAD

**Issue by TriangleToo** [Wruczek/ts-website#53]
Hello, after a ~3months of using this website, the cache folder generated a lot of folders with a probably scam, xxx and another websites. There's a lot of folders like nulled.io, xxxblog.to etc. How to fix the problem?

**Comment by avsaponchik** [comment]
an apache access.log would be super great to see
temporary solution: create a cronjob for /cache folder cleanup every midnight

**Comment by xSkyeX** [comment]
Its empty.

**Comment by TriangleToo** [comment]
https://pastebin.com/deA6qWTU

I have a lot of access.log files, its caused by using a banner, which users are getting every 1minute, so. It's hard to read all the logs.


/Created a cronjob for cleanup /cache, but it will be good to fix the problem with caching script.

**Comment by avsaponchik** [comment]
About that: same stuff happened to me. Uptimerobot started spamming my access.log with decent amount of connection logs (~5MB per day) So i just created the blank /uptimerobot.txt page with 'It works!' message in it; secondly - i edited uptimerobot's settings to update only blank .txt file (reduces load a bit); third - i edited apache config file with this:

	CustomLog ${APACHE_LOG_DIR}/access.log combined env=!dontlog
	SetEnvIf Request_URI "^/robots\.txt$" dontlog //to disable logging of robots.txt file
	SetEnvIf Request_URI "^/uptimerobot\.txt$" dontlog //and the same for uptimerobot.txt

You can set it up like me but only specifying your /banner/banner.php file.

sorry for my s**t english

**Comment by TriangleToo** [comment]
I'm using nginx

**Comment by avsaponchik** [comment]
https://www.bjornjohansen.no/exclude-requests-from-nginx-access-log

**Comment by Wruczek** [comment]
Looks like bykidi answered the question, thanks!

**Comment by avsaponchik** [comment]
@Wruczek actually, now his access.log will have less spam. But the point is that his ts-website /cache folder is still full of useless spam and i don't think that he can get rid of that on his own

**Comment by Wruczek** [comment]
2.0 have completely different caching mechanism, stores almost all data in a single file without subfolders. So I think we can say that this "issue" is "fixed".

**Comment by avsaponchik** [comment]
Glad to hear. Can we expect the closed alpha/beta test? :D

**Comment by Wruczek** [comment]
So far I don't have my PC and I cant work on the website :( But I will definitely post a closed beta on our Telegram group when I will have my pc back.
