### ISSUE TITLE
Module start/stop

### ISSUE THREAD

**Issue by Leto120** [Wruczek/ts-website#54]
Hello 
I you contact because I shall like knowing if a module with a start button and stop for a waiter ts3 will be available?
Thank you

**Comment by Wruczek** [comment]
What do you mean by a "module" and a "waiter"?

**Comment by Leto120** [comment]
As the server status, but inside the options to start or stop the server teamspeak 3

**Comment by Wruczek** [comment]
Definitely not in the current version. TS-website is not a ACP, for this to work you would need some sort of user authentication system to restrict it to admins only.

If you like, I can add it as a paid module just for you. If you are interested you can email me at wruczekk@gmail.com
