### ISSUE TITLE
XSS attacks

### ISSUE THREAD

**Issue by getbrainerror** [Wruczek/ts-website#57]
Hello,
its possible to use XSS in two ways.

How to reproduce this issue;
Possibility 1:
Just set as example the following string as a username which is part of the admin user groups:
`<script>alert('')</script>`
Now you just need to access the website.

Possibility 2:
Create a new ts identy with the following string as a username. Now you will need to ban this user from the ts server. Now access the ban.php site.

`<script>alert('')</script>`

best regards,
getBrainError

**Comment by pix0wl** [comment]
Nice find. 
You can add `.*[\<\>].*` as regular expression to your ban list for an temporary fix.

**Comment by getbrainerror** [comment]
I just added htmlspecialchars() at bans.php -> Line 71
`$user = (string)htmlspecialchars($ban['lastnickname']);`

**Comment by pix0wl** [comment]
Do you got a fix for the vulnerability via the viewer?

**Comment by Wruczek** [comment]
Thats a nice find! It's already fixed by design in 2.0, but I will definitely release a hotfix for 1.0 as well.
I've checked it and It affects adminlist and banlist, but not viewer as it already escapes html

**Comment by getbrainerror** [comment]
For the ban list i did the following changes:

include/adminlist.php -> Line 66
` $offlineClients[] = '<p><span class="label label-primary iconspacer">' . htmlspecialchars($userInfo['client_nickname']) . '</span><span class="label label-danger pull-right">' . translate($lang["adminlist"]["status"]["offline"]) . '</span></p>';`

include/adminlist.php -> Line 70
` $onlineClients[] = '<p><img src="lib/ts3phpframework/images/viewer/' . $user->getIcon() . '.png" alt="User status">' . '<span class="label label-primary">' . htmlspecialchars($user) . '</span>' . ($user['client_away'] ? '<span class="label label-warning pull-right">' . translate($lang["adminlist"]["status"]["away"]) . '</span>' : '<span class="label label-success pull-right">' . translate($lang["adminlist"]["status"]["online"]) . '</span>') . '</p>';`

**Comment by Wruczek** [comment]
I've pushed an update. Please update your ts-website and thanks to @getbrainerror for reporting the issue!
