### ISSUE TITLE
0: invalid reply from the server - I using TeaSpeak

### ISSUE THREAD

**Issue by davidjaksa** [Wruczek/ts-website#79]
I started using TeaSpeak in the days, and now the website displaying this: '0: invalid reply from the server'
What's the problem? How to fix it?

TeaSpeak log:
[16:25:49] [ERROR] Query invalid read. Code: 0 errno: 0 msg: Success

Sorry for my bad English :P

**Comment by toster234** [comment]
You whether correctly completed the password and login to server admin query?

**Comment by davidjaksa** [comment]
Yes, I tested it with YatQa, I can't understand what happened.

Is this a TeaSpeak error?

**Comment by Bluscream** [comment]
Do you know what command is causing the error?

**Comment by Wruczek** [comment]
In TeaSpeak there are a lot of changes in the query interface compared to the official server. Its not a simple drop-in replacement.

While ts3phpframework [added](https://github.com/planetteamspeak/ts3phpframework/commit/182508b670af54d7f3bdd4a1d432497a483d8ddf) "partial" support for TeaSpeak servers, its still not as simple as just replacing the library. A lot of things differ and I would need to change a lot to make it work. It's even harder to change when the code is an outdated procedural-style mess as it is now (duh).

Not sure when I will release 2.0 but TeaSpeak will be tested and supported in it.

**Comment by davidjaksa** [comment]
So what to do?

**Comment by Wruczek** [comment]
Wait for 2.0 or fix the current version yourself

**Comment by davidjaksa** [comment]
Hmm...

Idk how to fix it :/
Can you tell me?
When you release the 2.0?

**Comment by davidjaksa** [comment]
Today I started using TeamSpeak again. Thanks for the help!

**Comment by Wruczek** [comment]
Cool!
Keeping the issue open as it is still relevant

**Comment by derrobin154** [comment]
What is TeaSpeak o.O?

**Comment by Bluscream** [comment]
Google it

**Comment by davidjaksa** [comment]
:D I no longer using TeaSpeak

**Comment by davidjaksa** [comment]
Google it :D

**Comment by Bluscream** [comment]
Any news to this @Wruczek ?

![grafik](https://user-images.githubusercontent.com/3318223/39520554-a2946ee6-4dfa-11e8-800b-7a6bf5b1dcd7.png)
![grafik](https://user-images.githubusercontent.com/3318223/39521365-ca0477f2-4dfd-11e8-8635-f928bc675cfc.png)

**Comment by Wruczek** [comment]
Seems like the TeamSpeak 3 PHP Framework officially supports TeaSpeak now. So if you are having any issues with Tea, please report it [on their issue tracker](https://github.com/planetteamspeak/ts3phpframework/issues).


I've tested the current support, and seems like everything except for `servergroupclientlist` is working. Due to that, admin list and group assigner will throw an error.
