### ISSUE TITLE
Issue with address tab

### ISSUE THREAD

**Issue by lanceq1337** [Wruczek/ts-website#8]
So I have a problem with the script correctly typed in the config host, port and all the data. The script still does not recognizes the server. Also there is following error: An error occured! 0: php_network_getaddresses: getaddrinfo failed: Name or service not know

You can see issue there: http://ts.lanceq.pl/

**Comment by Wruczek** [comment]
How are you connecting to the server? Using hostname or IP address?
Post your teamspeak -> host from your config.

**Comment by lanceq1337** [comment]
I tried both, IP and localhost, still same error.

$config['teamspeak']['host']          = '91.134.134.212';          // TeamSpeak host address
$config['teamspeak']['login']         = 'serveradmin';        // Login
$config['teamspeak']['password']      = 'ojasd@iojs922';           // Password
$config['teamspeak']['server_port']   = 9987;                 // TeamSpeak server port
$config['teamspeak']['query_port']    = 10011;                // Query port
$config['teamspeak']['displayip']     = 'ts.lanceq.pl';       // IP shown to users and used for connections

**Comment by lanceq1337** [comment]
I tried both, IP and localhost, still same error.

$config['teamspeak']['host']          = '91.134.134.212';          // TeamSpeak host address
$config['teamspeak']['login']         = 'serveradmin';        // Login
$config['teamspeak']['password']      = 'XXXXXXX';           // Password
$config['teamspeak']['server_port']   = 9987;                 // TeamSpeak server port
$config['teamspeak']['query_port']    = 10011;                // Query port
$config['teamspeak']['displayip']     = 'ts.lanceq.pl';       // IP shown to users and used for connections

**Comment by Wruczek** [comment]
You are hosting Teamspeak server and website on the same server?

**Comment by lanceq1337** [comment]
Yes.

**Comment by Wruczek** [comment]
Then try setting "127.0.0.1" in teamspeak -> host

**Comment by lanceq1337** [comment]
Same with the:

$config['teamspeak']['host']          = '127.0.0.1';          // TeamSpeak host address

**Comment by Wruczek** [comment]
There's definitely a problem with your server.
One more thing I can try to do is looking at phpinfo.
Can you post it here / give me a link to view it?

1. Create new .php file
2. Put ``<?php phpinfo();`` inside of it
3. Link me to the website or send me the output

**Comment by lanceq1337** [comment]
http://ts.lanceq.pl/info.php

**Comment by Wruczek** [comment]
I'm sorry, but I can't really help here. Everything looks OK, website should work flawlessly using your local address (127.0.0.1). There's something misconfigured on your server.

The only last advice I can give you is googling the issue and trying what other people suggests.
- http://stackoverflow.com/a/6361464
- http://bit.ly/2dxu8lv

If nothing works, you can try hosting the website elsewhere.
