### ISSUE TITLE
Ts3 Server ShutDown Because of The Site

### ISSUE THREAD

**Issue by Xelofan** [Wruczek/ts-website#89]
# Hey, everyone!
When i upload the site onto my vps, then i configure it, the server shuts down randomly.
The log only says: 

> server shut down.

**What can I do with that ?**

_Btw, i really like this site, keep up the good work!_

**Comment by Bluscream** [comment]
Maybe give some more of the log?

**Comment by Xelofan** [comment]
Okay, it looks like i fixed the problem, but @Bluscream , thanks.
