### ISSUE TITLE
help me plz

### ISSUE THREAD

**Issue by mehdi0121** [Wruczek/ts-website#91]
![sv](https://user-images.githubusercontent.com/41438090/42947259-37e3371a-8b82-11e8-8e0a-baf941efdd5c.jpg)

how to fix ?
plz help me!

**Comment by toster234** [comment]
It is written what is wrong and what you need to do.

**Comment by toster234** [comment]
![bez tytulu12](https://user-images.githubusercontent.com/26941529/42947810-6ddedaae-8b6e-11e8-88d3-60b9c7c7aaff.png)
![bez tytulu](https://user-images.githubusercontent.com/26941529/42947809-6db2ed4a-8b6e-11e8-9349-34438c2a98c4.png)

**Comment by mehdi0121** [comment]
![sv1](https://user-images.githubusercontent.com/41438090/42948627-2611f7da-8b85-11e8-808d-a98688be6424.jpg)
i cant see!
:\

**Comment by toster234** [comment]
change permissions

**Comment by mehdi0121** [comment]
how ?

**Comment by toster234** [comment]
![image](https://user-images.githubusercontent.com/26941529/42949114-56d3a3dc-8b71-11e8-9367-aa5b70017a67.png)

**Comment by mehdi0121** [comment]
tnx for help

**Comment by toster234** [comment]
Why you use web file menager... Create ftp user or sftp and connect by using WinSCP. That was be easier

**Comment by mehdi0121** [comment]
My hosting is broken

**Comment by mehdi0121** [comment]
![ab](https://user-images.githubusercontent.com/41438090/42950137-9abedd52-8b88-11e8-8366-a5f6b74ac446.jpg)
Another problem...

**Comment by Wruczek** [comment]
It might happen if you are using free or cheap hosting. They often block sockets to prevent abuse.

**Comment by mehdi0121** [comment]
What to do now

**Comment by mehdi0121** [comment]
؟

**Comment by Wruczek** [comment]
You should get a good hosting and make sure they allow sockets. Or just simply install it on your VPS with nginx.

**Comment by mehdi0121** [comment]
why?

**Comment by mehdi0121** [comment]
I bought a new hosting but it has problems

**Comment by Wruczek** [comment]
1. Sockets might be closed on your hosting
2. You have not properly configured connection to your TeamSpeak server
3. If you are using shared TeamSpeak hosting, they might completely block TeamSpeak query.
