### ISSUE TITLE
Sqlite3 compatibility

### ISSUE THREAD

**Issue by Bischi1997** [Wruczek/ts-website#96]
First of thanks for this awesome site, I really appreciate your work.
Is there a possibility to connect to an sqlite database? If so, how do I do this?

**Comment by Wruczek** [comment]
Thanks for your kind words!

Why would you need sqlite? Do you want to store some other data there?

**Comment by Bischi1997** [comment]
I got it to work. I did not quiet understand the system . It actually works as intended. No need for this Issue. Sorry...

Issue was, that I got an error connecting. This was resolved by adding my IP to the whitelist of teamspeak and changing the ts IP in the conf file to the external one (was previously 127.0.0.1). 

I was thinking it was directly connecting to the database, which is not the case.

**Comment by Wruczek** [comment]
Yeah, if you have connection issues then it's not related to the teamspeak backend you are using, they all provide server query. Glad you got that resolved :)
