### ISSUE TITLE
Group Assigner

### ISSUE THREAD

**Issue by PWNYYY** [Wruczek/ts-website#98]
Hey, 
wo kann ich die Gruppen ID's etc.
eintragen?
Ich habe es in der Datenbank schon mal
probiert nur passiert dort nichts.

LG.

**Comment by derrobin154** [comment]
Dort lohnt es sich das Wiki mal durchzulesen.
https://github.com/Wruczek/ts-website/wiki/%5BDE%5D-Installation-von-ts-website-%5B2.x%5D

**Comment by PWNYYY** [comment]
Besten Dank!

**Comment by zockparadies** [comment]
Hey, ich habe das Problem dass ich bei dem Group Assigner nicht schlau werde.
Wo muss ich die Gruppen einfügen?

```
[
    {
        "name": "Games",
        "icon": "",
        "max": 1,
        "groups": [
            185,
            187
        ]
    },
]
```

Könnte mir jemand ein Beispiel zeigen? Bin langsam am verzweifeln, seit stunden probiere ich und ich schaff es einfach nicht -.-

**Comment by toster234** [comment]
In English.

> Hey, ich habe das Problem dass ich bei dem Group Assigner nicht schlau werde.
> Wo muss ich die Gruppen einfügen?
> 
> [
> {
> "name": "Games",
> "icon": "",
> "max": 1,
> "groups": [
> 185,
> 187
> ]
> },
> ]
> 
> Könnte mir jemand ein Beispiel zeigen? Bin langsam am verzweifeln, seit stunden probiere ich und ich schaff es einfach nicht -.-

**Comment by PWNYYY** [comment]
Bitteschön

```
[
    {
        "name": "Age",
        "icon": "fas fa-globe",
        "max": 1,
        "groups": [
            18,
            19,
            20,
            40,
            388
        ]
    },
    {
        "name": "Games",
        "icon": "fas fa-gamepad",
        "max": 4,
        "groups": [
            16,
            17,
            41,
            42,
            625,
            655
        ]
    },
    {
        "name": "Specials",
        "icon": "",
        "max": 2,
        "groups": [
            28,
            29,
            629,
            618,
            653,
            757
        ]
    }
]
```
